// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Eldarrin/nexus-go-api/models"
)

// NewCreateRGroupRepositoryParams creates a new CreateRGroupRepositoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateRGroupRepositoryParams() *CreateRGroupRepositoryParams {
	return &CreateRGroupRepositoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateRGroupRepositoryParamsWithTimeout creates a new CreateRGroupRepositoryParams object
// with the ability to set a timeout on a request.
func NewCreateRGroupRepositoryParamsWithTimeout(timeout time.Duration) *CreateRGroupRepositoryParams {
	return &CreateRGroupRepositoryParams{
		timeout: timeout,
	}
}

// NewCreateRGroupRepositoryParamsWithContext creates a new CreateRGroupRepositoryParams object
// with the ability to set a context for a request.
func NewCreateRGroupRepositoryParamsWithContext(ctx context.Context) *CreateRGroupRepositoryParams {
	return &CreateRGroupRepositoryParams{
		Context: ctx,
	}
}

// NewCreateRGroupRepositoryParamsWithHTTPClient creates a new CreateRGroupRepositoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateRGroupRepositoryParamsWithHTTPClient(client *http.Client) *CreateRGroupRepositoryParams {
	return &CreateRGroupRepositoryParams{
		HTTPClient: client,
	}
}

/*
CreateRGroupRepositoryParams contains all the parameters to send to the API endpoint

	for the create repository 31 operation.

	Typically these are written to a http.Request.
*/
type CreateRGroupRepositoryParams struct {

	// Body.
	Body *models.RGroupRepositoryAPIRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create repository 31 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateRGroupRepositoryParams) WithDefaults() *CreateRGroupRepositoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create repository 31 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateRGroupRepositoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create repository 31 params
func (o *CreateRGroupRepositoryParams) WithTimeout(timeout time.Duration) *CreateRGroupRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create repository 31 params
func (o *CreateRGroupRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create repository 31 params
func (o *CreateRGroupRepositoryParams) WithContext(ctx context.Context) *CreateRGroupRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create repository 31 params
func (o *CreateRGroupRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create repository 31 params
func (o *CreateRGroupRepositoryParams) WithHTTPClient(client *http.Client) *CreateRGroupRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create repository 31 params
func (o *CreateRGroupRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create repository 31 params
func (o *CreateRGroupRepositoryParams) WithBody(body *models.RGroupRepositoryAPIRequest) *CreateRGroupRepositoryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create repository 31 params
func (o *CreateRGroupRepositoryParams) SetBody(body *models.RGroupRepositoryAPIRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateRGroupRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
