// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Eldarrin/nexus-go-api/models"
)

// NewCreateMavenProxyRepositoryParams creates a new CreateMavenProxyRepositoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateMavenProxyRepositoryParams() *CreateMavenProxyRepositoryParams {
	return &CreateMavenProxyRepositoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateMavenProxyRepositoryParamsWithTimeout creates a new CreateMavenProxyRepositoryParams object
// with the ability to set a timeout on a request.
func NewCreateMavenProxyRepositoryParamsWithTimeout(timeout time.Duration) *CreateMavenProxyRepositoryParams {
	return &CreateMavenProxyRepositoryParams{
		timeout: timeout,
	}
}

// NewCreateMavenProxyRepositoryParamsWithContext creates a new CreateMavenProxyRepositoryParams object
// with the ability to set a context for a request.
func NewCreateMavenProxyRepositoryParamsWithContext(ctx context.Context) *CreateMavenProxyRepositoryParams {
	return &CreateMavenProxyRepositoryParams{
		Context: ctx,
	}
}

// NewCreateMavenProxyRepositoryParamsWithHTTPClient creates a new CreateMavenProxyRepositoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateMavenProxyRepositoryParamsWithHTTPClient(client *http.Client) *CreateMavenProxyRepositoryParams {
	return &CreateMavenProxyRepositoryParams{
		HTTPClient: client,
	}
}

/*
CreateMavenProxyRepositoryParams contains all the parameters to send to the API endpoint

	for the create repository 2 operation.

	Typically these are written to a http.Request.
*/
type CreateMavenProxyRepositoryParams struct {

	// Body.
	Body *models.MavenProxyRepositoryAPIRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create repository 2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateMavenProxyRepositoryParams) WithDefaults() *CreateMavenProxyRepositoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create repository 2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateMavenProxyRepositoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create repository 2 params
func (o *CreateMavenProxyRepositoryParams) WithTimeout(timeout time.Duration) *CreateMavenProxyRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create repository 2 params
func (o *CreateMavenProxyRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create repository 2 params
func (o *CreateMavenProxyRepositoryParams) WithContext(ctx context.Context) *CreateMavenProxyRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create repository 2 params
func (o *CreateMavenProxyRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create repository 2 params
func (o *CreateMavenProxyRepositoryParams) WithHTTPClient(client *http.Client) *CreateMavenProxyRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create repository 2 params
func (o *CreateMavenProxyRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create repository 2 params
func (o *CreateMavenProxyRepositoryParams) WithBody(body *models.MavenProxyRepositoryAPIRequest) *CreateMavenProxyRepositoryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create repository 2 params
func (o *CreateMavenProxyRepositoryParams) SetBody(body *models.MavenProxyRepositoryAPIRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateMavenProxyRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
