// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Eldarrin/nexus-go-api/models"
)

// NewCreateRubyGemsGroupRepositoryParams creates a new CreateRubyGemsGroupRepositoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateRubyGemsGroupRepositoryParams() *CreateRubyGemsGroupRepositoryParams {
	return &CreateRubyGemsGroupRepositoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateRubyGemsGroupRepositoryParamsWithTimeout creates a new CreateRubyGemsGroupRepositoryParams object
// with the ability to set a timeout on a request.
func NewCreateRubyGemsGroupRepositoryParamsWithTimeout(timeout time.Duration) *CreateRubyGemsGroupRepositoryParams {
	return &CreateRubyGemsGroupRepositoryParams{
		timeout: timeout,
	}
}

// NewCreateRubyGemsGroupRepositoryParamsWithContext creates a new CreateRubyGemsGroupRepositoryParams object
// with the ability to set a context for a request.
func NewCreateRubyGemsGroupRepositoryParamsWithContext(ctx context.Context) *CreateRubyGemsGroupRepositoryParams {
	return &CreateRubyGemsGroupRepositoryParams{
		Context: ctx,
	}
}

// NewCreateRubyGemsGroupRepositoryParamsWithHTTPClient creates a new CreateRubyGemsGroupRepositoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateRubyGemsGroupRepositoryParamsWithHTTPClient(client *http.Client) *CreateRubyGemsGroupRepositoryParams {
	return &CreateRubyGemsGroupRepositoryParams{
		HTTPClient: client,
	}
}

/*
CreateRubyGemsGroupRepositoryParams contains all the parameters to send to the API endpoint

	for the create repository 14 operation.

	Typically these are written to a http.Request.
*/
type CreateRubyGemsGroupRepositoryParams struct {

	// Body.
	Body *models.RubyGemsGroupRepositoryAPIRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create repository 14 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateRubyGemsGroupRepositoryParams) WithDefaults() *CreateRubyGemsGroupRepositoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create repository 14 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateRubyGemsGroupRepositoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create repository 14 params
func (o *CreateRubyGemsGroupRepositoryParams) WithTimeout(timeout time.Duration) *CreateRubyGemsGroupRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create repository 14 params
func (o *CreateRubyGemsGroupRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create repository 14 params
func (o *CreateRubyGemsGroupRepositoryParams) WithContext(ctx context.Context) *CreateRubyGemsGroupRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create repository 14 params
func (o *CreateRubyGemsGroupRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create repository 14 params
func (o *CreateRubyGemsGroupRepositoryParams) WithHTTPClient(client *http.Client) *CreateRubyGemsGroupRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create repository 14 params
func (o *CreateRubyGemsGroupRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create repository 14 params
func (o *CreateRubyGemsGroupRepositoryParams) WithBody(body *models.RubyGemsGroupRepositoryAPIRequest) *CreateRubyGemsGroupRepositoryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create repository 14 params
func (o *CreateRubyGemsGroupRepositoryParams) SetBody(body *models.RubyGemsGroupRepositoryAPIRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateRubyGemsGroupRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
