// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateRGroupRepositoryReader is a Reader for the CreateRGroupRepository structure.
type CreateRGroupRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateRGroupRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateRGroupRepositoryCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateRGroupRepositoryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateRGroupRepositoryForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewCreateRGroupRepositoryMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateRGroupRepositoryCreated creates a CreateRGroupRepositoryCreated with default headers values
func NewCreateRGroupRepositoryCreated() *CreateRGroupRepositoryCreated {
	return &CreateRGroupRepositoryCreated{}
}

/*
	CreateRGroupRepositoryCreated describes a response with status code 201, with default header values.

Repository created
*/
type CreateRGroupRepositoryCreated struct {
}

// IsSuccess returns true when this create repository31 created response has a 2xx status code
func (o *CreateRGroupRepositoryCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create repository31 created response has a 3xx status code
func (o *CreateRGroupRepositoryCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository31 created response has a 4xx status code
func (o *CreateRGroupRepositoryCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create repository31 created response has a 5xx status code
func (o *CreateRGroupRepositoryCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository31 created response a status code equal to that given
func (o *CreateRGroupRepositoryCreated) IsCode(code int) bool {
	return code == 201
}

func (o *CreateRGroupRepositoryCreated) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/r/group][%d] createRepository31Created ", 201)
}

func (o *CreateRGroupRepositoryCreated) String() string {
	return fmt.Sprintf("[POST /v1/repositories/r/group][%d] createRepository31Created ", 201)
}

func (o *CreateRGroupRepositoryCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateRGroupRepositoryUnauthorized creates a CreateRGroupRepositoryUnauthorized with default headers values
func NewCreateRGroupRepositoryUnauthorized() *CreateRGroupRepositoryUnauthorized {
	return &CreateRGroupRepositoryUnauthorized{}
}

/*
	CreateRGroupRepositoryUnauthorized describes a response with status code 401, with default header values.

Authentication required
*/
type CreateRGroupRepositoryUnauthorized struct {
}

// IsSuccess returns true when this create repository31 unauthorized response has a 2xx status code
func (o *CreateRGroupRepositoryUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository31 unauthorized response has a 3xx status code
func (o *CreateRGroupRepositoryUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository31 unauthorized response has a 4xx status code
func (o *CreateRGroupRepositoryUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository31 unauthorized response has a 5xx status code
func (o *CreateRGroupRepositoryUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository31 unauthorized response a status code equal to that given
func (o *CreateRGroupRepositoryUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *CreateRGroupRepositoryUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/r/group][%d] createRepository31Unauthorized ", 401)
}

func (o *CreateRGroupRepositoryUnauthorized) String() string {
	return fmt.Sprintf("[POST /v1/repositories/r/group][%d] createRepository31Unauthorized ", 401)
}

func (o *CreateRGroupRepositoryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateRGroupRepositoryForbidden creates a CreateRGroupRepositoryForbidden with default headers values
func NewCreateRGroupRepositoryForbidden() *CreateRGroupRepositoryForbidden {
	return &CreateRGroupRepositoryForbidden{}
}

/*
	CreateRGroupRepositoryForbidden describes a response with status code 403, with default header values.

Insufficient permissions
*/
type CreateRGroupRepositoryForbidden struct {
}

// IsSuccess returns true when this create repository31 forbidden response has a 2xx status code
func (o *CreateRGroupRepositoryForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository31 forbidden response has a 3xx status code
func (o *CreateRGroupRepositoryForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository31 forbidden response has a 4xx status code
func (o *CreateRGroupRepositoryForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository31 forbidden response has a 5xx status code
func (o *CreateRGroupRepositoryForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository31 forbidden response a status code equal to that given
func (o *CreateRGroupRepositoryForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *CreateRGroupRepositoryForbidden) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/r/group][%d] createRepository31Forbidden ", 403)
}

func (o *CreateRGroupRepositoryForbidden) String() string {
	return fmt.Sprintf("[POST /v1/repositories/r/group][%d] createRepository31Forbidden ", 403)
}

func (o *CreateRGroupRepositoryForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateRGroupRepositoryMethodNotAllowed creates a CreateRGroupRepositoryMethodNotAllowed with default headers values
func NewCreateRGroupRepositoryMethodNotAllowed() *CreateRGroupRepositoryMethodNotAllowed {
	return &CreateRGroupRepositoryMethodNotAllowed{}
}

/*
	CreateRGroupRepositoryMethodNotAllowed describes a response with status code 405, with default header values.

Feature is disabled in High Availability
*/
type CreateRGroupRepositoryMethodNotAllowed struct {
}

// IsSuccess returns true when this create repository31 method not allowed response has a 2xx status code
func (o *CreateRGroupRepositoryMethodNotAllowed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository31 method not allowed response has a 3xx status code
func (o *CreateRGroupRepositoryMethodNotAllowed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository31 method not allowed response has a 4xx status code
func (o *CreateRGroupRepositoryMethodNotAllowed) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository31 method not allowed response has a 5xx status code
func (o *CreateRGroupRepositoryMethodNotAllowed) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository31 method not allowed response a status code equal to that given
func (o *CreateRGroupRepositoryMethodNotAllowed) IsCode(code int) bool {
	return code == 405
}

func (o *CreateRGroupRepositoryMethodNotAllowed) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/r/group][%d] createRepository31MethodNotAllowed ", 405)
}

func (o *CreateRGroupRepositoryMethodNotAllowed) String() string {
	return fmt.Sprintf("[POST /v1/repositories/r/group][%d] createRepository31MethodNotAllowed ", 405)
}

func (o *CreateRGroupRepositoryMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
