// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateHelmProxyRepositoryReader is a Reader for the CreateHelmProxyRepository structure.
type CreateHelmProxyRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateHelmProxyRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateHelmProxyRepositoryCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateHelmProxyRepositoryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateHelmProxyRepositoryForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewCreateHelmProxyRepositoryMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateHelmProxyRepositoryCreated creates a CreateHelmProxyRepositoryCreated with default headers values
func NewCreateHelmProxyRepositoryCreated() *CreateHelmProxyRepositoryCreated {
	return &CreateHelmProxyRepositoryCreated{}
}

/*
	CreateHelmProxyRepositoryCreated describes a response with status code 201, with default header values.

Repository created
*/
type CreateHelmProxyRepositoryCreated struct {
}

// IsSuccess returns true when this create repository24 created response has a 2xx status code
func (o *CreateHelmProxyRepositoryCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create repository24 created response has a 3xx status code
func (o *CreateHelmProxyRepositoryCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository24 created response has a 4xx status code
func (o *CreateHelmProxyRepositoryCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create repository24 created response has a 5xx status code
func (o *CreateHelmProxyRepositoryCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository24 created response a status code equal to that given
func (o *CreateHelmProxyRepositoryCreated) IsCode(code int) bool {
	return code == 201
}

func (o *CreateHelmProxyRepositoryCreated) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/helm/proxy][%d] createRepository24Created ", 201)
}

func (o *CreateHelmProxyRepositoryCreated) String() string {
	return fmt.Sprintf("[POST /v1/repositories/helm/proxy][%d] createRepository24Created ", 201)
}

func (o *CreateHelmProxyRepositoryCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateHelmProxyRepositoryUnauthorized creates a CreateHelmProxyRepositoryUnauthorized with default headers values
func NewCreateHelmProxyRepositoryUnauthorized() *CreateHelmProxyRepositoryUnauthorized {
	return &CreateHelmProxyRepositoryUnauthorized{}
}

/*
	CreateHelmProxyRepositoryUnauthorized describes a response with status code 401, with default header values.

Authentication required
*/
type CreateHelmProxyRepositoryUnauthorized struct {
}

// IsSuccess returns true when this create repository24 unauthorized response has a 2xx status code
func (o *CreateHelmProxyRepositoryUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository24 unauthorized response has a 3xx status code
func (o *CreateHelmProxyRepositoryUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository24 unauthorized response has a 4xx status code
func (o *CreateHelmProxyRepositoryUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository24 unauthorized response has a 5xx status code
func (o *CreateHelmProxyRepositoryUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository24 unauthorized response a status code equal to that given
func (o *CreateHelmProxyRepositoryUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *CreateHelmProxyRepositoryUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/helm/proxy][%d] createRepository24Unauthorized ", 401)
}

func (o *CreateHelmProxyRepositoryUnauthorized) String() string {
	return fmt.Sprintf("[POST /v1/repositories/helm/proxy][%d] createRepository24Unauthorized ", 401)
}

func (o *CreateHelmProxyRepositoryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateHelmProxyRepositoryForbidden creates a CreateHelmProxyRepositoryForbidden with default headers values
func NewCreateHelmProxyRepositoryForbidden() *CreateHelmProxyRepositoryForbidden {
	return &CreateHelmProxyRepositoryForbidden{}
}

/*
	CreateHelmProxyRepositoryForbidden describes a response with status code 403, with default header values.

Insufficient permissions
*/
type CreateHelmProxyRepositoryForbidden struct {
}

// IsSuccess returns true when this create repository24 forbidden response has a 2xx status code
func (o *CreateHelmProxyRepositoryForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository24 forbidden response has a 3xx status code
func (o *CreateHelmProxyRepositoryForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository24 forbidden response has a 4xx status code
func (o *CreateHelmProxyRepositoryForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository24 forbidden response has a 5xx status code
func (o *CreateHelmProxyRepositoryForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository24 forbidden response a status code equal to that given
func (o *CreateHelmProxyRepositoryForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *CreateHelmProxyRepositoryForbidden) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/helm/proxy][%d] createRepository24Forbidden ", 403)
}

func (o *CreateHelmProxyRepositoryForbidden) String() string {
	return fmt.Sprintf("[POST /v1/repositories/helm/proxy][%d] createRepository24Forbidden ", 403)
}

func (o *CreateHelmProxyRepositoryForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateHelmProxyRepositoryMethodNotAllowed creates a CreateHelmProxyRepositoryMethodNotAllowed with default headers values
func NewCreateHelmProxyRepositoryMethodNotAllowed() *CreateHelmProxyRepositoryMethodNotAllowed {
	return &CreateHelmProxyRepositoryMethodNotAllowed{}
}

/*
	CreateHelmProxyRepositoryMethodNotAllowed describes a response with status code 405, with default header values.

Feature is disabled in High Availability
*/
type CreateHelmProxyRepositoryMethodNotAllowed struct {
}

// IsSuccess returns true when this create repository24 method not allowed response has a 2xx status code
func (o *CreateHelmProxyRepositoryMethodNotAllowed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository24 method not allowed response has a 3xx status code
func (o *CreateHelmProxyRepositoryMethodNotAllowed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository24 method not allowed response has a 4xx status code
func (o *CreateHelmProxyRepositoryMethodNotAllowed) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository24 method not allowed response has a 5xx status code
func (o *CreateHelmProxyRepositoryMethodNotAllowed) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository24 method not allowed response a status code equal to that given
func (o *CreateHelmProxyRepositoryMethodNotAllowed) IsCode(code int) bool {
	return code == 405
}

func (o *CreateHelmProxyRepositoryMethodNotAllowed) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/helm/proxy][%d] createRepository24MethodNotAllowed ", 405)
}

func (o *CreateHelmProxyRepositoryMethodNotAllowed) String() string {
	return fmt.Sprintf("[POST /v1/repositories/helm/proxy][%d] createRepository24MethodNotAllowed ", 405)
}

func (o *CreateHelmProxyRepositoryMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
