// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Eldarrin/nexus-go-api/models"
)

// NewCreateAptHostedRepositoryParams creates a new CreateAptHostedRepositoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateAptHostedRepositoryParams() *CreateAptHostedRepositoryParams {
	return &CreateAptHostedRepositoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateAptHostedRepositoryParamsWithTimeout creates a new CreateAptHostedRepositoryParams object
// with the ability to set a timeout on a request.
func NewCreateAptHostedRepositoryParamsWithTimeout(timeout time.Duration) *CreateAptHostedRepositoryParams {
	return &CreateAptHostedRepositoryParams{
		timeout: timeout,
	}
}

// NewCreateAptHostedRepositoryParamsWithContext creates a new CreateAptHostedRepositoryParams object
// with the ability to set a context for a request.
func NewCreateAptHostedRepositoryParamsWithContext(ctx context.Context) *CreateAptHostedRepositoryParams {
	return &CreateAptHostedRepositoryParams{
		Context: ctx,
	}
}

// NewCreateAptHostedRepositoryParamsWithHTTPClient creates a new CreateAptHostedRepositoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateAptHostedRepositoryParamsWithHTTPClient(client *http.Client) *CreateAptHostedRepositoryParams {
	return &CreateAptHostedRepositoryParams{
		HTTPClient: client,
	}
}

/*
CreateAptHostedRepositoryParams contains all the parameters to send to the API endpoint

	for the create repository 3 operation.

	Typically these are written to a http.Request.
*/
type CreateAptHostedRepositoryParams struct {

	// Body.
	Body *models.AptHostedRepositoryAPIRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create repository 3 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateAptHostedRepositoryParams) WithDefaults() *CreateAptHostedRepositoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create repository 3 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateAptHostedRepositoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create repository 3 params
func (o *CreateAptHostedRepositoryParams) WithTimeout(timeout time.Duration) *CreateAptHostedRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create repository 3 params
func (o *CreateAptHostedRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create repository 3 params
func (o *CreateAptHostedRepositoryParams) WithContext(ctx context.Context) *CreateAptHostedRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create repository 3 params
func (o *CreateAptHostedRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create repository 3 params
func (o *CreateAptHostedRepositoryParams) WithHTTPClient(client *http.Client) *CreateAptHostedRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create repository 3 params
func (o *CreateAptHostedRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create repository 3 params
func (o *CreateAptHostedRepositoryParams) WithBody(body *models.AptHostedRepositoryAPIRequest) *CreateAptHostedRepositoryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create repository 3 params
func (o *CreateAptHostedRepositoryParams) SetBody(body *models.AptHostedRepositoryAPIRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateAptHostedRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
