// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreatePypiProxyRepositoryReader is a Reader for the CreatePypiProxyRepository structure.
type CreatePypiProxyRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreatePypiProxyRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreatePypiProxyRepositoryCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreatePypiProxyRepositoryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreatePypiProxyRepositoryForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreatePypiProxyRepositoryCreated creates a CreatePypiProxyRepositoryCreated with default headers values
func NewCreatePypiProxyRepositoryCreated() *CreatePypiProxyRepositoryCreated {
	return &CreatePypiProxyRepositoryCreated{}
}

/*
	CreatePypiProxyRepositoryCreated describes a response with status code 201, with default header values.

Repository created
*/
type CreatePypiProxyRepositoryCreated struct {
}

// IsSuccess returns true when this create repository28 created response has a 2xx status code
func (o *CreatePypiProxyRepositoryCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create repository28 created response has a 3xx status code
func (o *CreatePypiProxyRepositoryCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository28 created response has a 4xx status code
func (o *CreatePypiProxyRepositoryCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create repository28 created response has a 5xx status code
func (o *CreatePypiProxyRepositoryCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository28 created response a status code equal to that given
func (o *CreatePypiProxyRepositoryCreated) IsCode(code int) bool {
	return code == 201
}

func (o *CreatePypiProxyRepositoryCreated) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/pypi/proxy][%d] createRepository28Created ", 201)
}

func (o *CreatePypiProxyRepositoryCreated) String() string {
	return fmt.Sprintf("[POST /v1/repositories/pypi/proxy][%d] createRepository28Created ", 201)
}

func (o *CreatePypiProxyRepositoryCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreatePypiProxyRepositoryUnauthorized creates a CreatePypiProxyRepositoryUnauthorized with default headers values
func NewCreatePypiProxyRepositoryUnauthorized() *CreatePypiProxyRepositoryUnauthorized {
	return &CreatePypiProxyRepositoryUnauthorized{}
}

/*
	CreatePypiProxyRepositoryUnauthorized describes a response with status code 401, with default header values.

Authentication required
*/
type CreatePypiProxyRepositoryUnauthorized struct {
}

// IsSuccess returns true when this create repository28 unauthorized response has a 2xx status code
func (o *CreatePypiProxyRepositoryUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository28 unauthorized response has a 3xx status code
func (o *CreatePypiProxyRepositoryUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository28 unauthorized response has a 4xx status code
func (o *CreatePypiProxyRepositoryUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository28 unauthorized response has a 5xx status code
func (o *CreatePypiProxyRepositoryUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository28 unauthorized response a status code equal to that given
func (o *CreatePypiProxyRepositoryUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *CreatePypiProxyRepositoryUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/pypi/proxy][%d] createRepository28Unauthorized ", 401)
}

func (o *CreatePypiProxyRepositoryUnauthorized) String() string {
	return fmt.Sprintf("[POST /v1/repositories/pypi/proxy][%d] createRepository28Unauthorized ", 401)
}

func (o *CreatePypiProxyRepositoryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreatePypiProxyRepositoryForbidden creates a CreatePypiProxyRepositoryForbidden with default headers values
func NewCreatePypiProxyRepositoryForbidden() *CreatePypiProxyRepositoryForbidden {
	return &CreatePypiProxyRepositoryForbidden{}
}

/*
	CreatePypiProxyRepositoryForbidden describes a response with status code 403, with default header values.

Insufficient permissions
*/
type CreatePypiProxyRepositoryForbidden struct {
}

// IsSuccess returns true when this create repository28 forbidden response has a 2xx status code
func (o *CreatePypiProxyRepositoryForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository28 forbidden response has a 3xx status code
func (o *CreatePypiProxyRepositoryForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository28 forbidden response has a 4xx status code
func (o *CreatePypiProxyRepositoryForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository28 forbidden response has a 5xx status code
func (o *CreatePypiProxyRepositoryForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository28 forbidden response a status code equal to that given
func (o *CreatePypiProxyRepositoryForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *CreatePypiProxyRepositoryForbidden) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/pypi/proxy][%d] createRepository28Forbidden ", 403)
}

func (o *CreatePypiProxyRepositoryForbidden) String() string {
	return fmt.Sprintf("[POST /v1/repositories/pypi/proxy][%d] createRepository28Forbidden ", 403)
}

func (o *CreatePypiProxyRepositoryForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
