// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Eldarrin/nexus-go-api/models"
)

// NewCreateYumProxyRepositoryParams creates a new CreateYumProxyRepositoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateYumProxyRepositoryParams() *CreateYumProxyRepositoryParams {
	return &CreateYumProxyRepositoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateYumProxyRepositoryParamsWithTimeout creates a new CreateYumProxyRepositoryParams object
// with the ability to set a timeout on a request.
func NewCreateYumProxyRepositoryParamsWithTimeout(timeout time.Duration) *CreateYumProxyRepositoryParams {
	return &CreateYumProxyRepositoryParams{
		timeout: timeout,
	}
}

// NewCreateYumProxyRepositoryParamsWithContext creates a new CreateYumProxyRepositoryParams object
// with the ability to set a context for a request.
func NewCreateYumProxyRepositoryParamsWithContext(ctx context.Context) *CreateYumProxyRepositoryParams {
	return &CreateYumProxyRepositoryParams{
		Context: ctx,
	}
}

// NewCreateYumProxyRepositoryParamsWithHTTPClient creates a new CreateYumProxyRepositoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateYumProxyRepositoryParamsWithHTTPClient(client *http.Client) *CreateYumProxyRepositoryParams {
	return &CreateYumProxyRepositoryParams{
		HTTPClient: client,
	}
}

/*
CreateYumProxyRepositoryParams contains all the parameters to send to the API endpoint

	for the create repository 22 operation.

	Typically these are written to a http.Request.
*/
type CreateYumProxyRepositoryParams struct {

	// Body.
	Body *models.YumProxyRepositoryAPIRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create repository 22 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateYumProxyRepositoryParams) WithDefaults() *CreateYumProxyRepositoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create repository 22 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateYumProxyRepositoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create repository 22 params
func (o *CreateYumProxyRepositoryParams) WithTimeout(timeout time.Duration) *CreateYumProxyRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create repository 22 params
func (o *CreateYumProxyRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create repository 22 params
func (o *CreateYumProxyRepositoryParams) WithContext(ctx context.Context) *CreateYumProxyRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create repository 22 params
func (o *CreateYumProxyRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create repository 22 params
func (o *CreateYumProxyRepositoryParams) WithHTTPClient(client *http.Client) *CreateYumProxyRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create repository 22 params
func (o *CreateYumProxyRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create repository 22 params
func (o *CreateYumProxyRepositoryParams) WithBody(body *models.YumProxyRepositoryAPIRequest) *CreateYumProxyRepositoryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create repository 22 params
func (o *CreateYumProxyRepositoryParams) SetBody(body *models.YumProxyRepositoryAPIRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateYumProxyRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
