// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateCondaProxyRepositoryReader is a Reader for the CreateCondaProxyRepository structure.
type CreateCondaProxyRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateCondaProxyRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateCondaProxyRepositoryCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateCondaProxyRepositoryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateCondaProxyRepositoryForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewCreateCondaProxyRepositoryMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateCondaProxyRepositoryCreated creates a CreateCondaProxyRepositoryCreated with default headers values
func NewCreateCondaProxyRepositoryCreated() *CreateCondaProxyRepositoryCreated {
	return &CreateCondaProxyRepositoryCreated{}
}

/*
	CreateCondaProxyRepositoryCreated describes a response with status code 201, with default header values.

Repository created
*/
type CreateCondaProxyRepositoryCreated struct {
}

// IsSuccess returns true when this create repository29 created response has a 2xx status code
func (o *CreateCondaProxyRepositoryCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create repository29 created response has a 3xx status code
func (o *CreateCondaProxyRepositoryCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository29 created response has a 4xx status code
func (o *CreateCondaProxyRepositoryCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create repository29 created response has a 5xx status code
func (o *CreateCondaProxyRepositoryCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository29 created response a status code equal to that given
func (o *CreateCondaProxyRepositoryCreated) IsCode(code int) bool {
	return code == 201
}

func (o *CreateCondaProxyRepositoryCreated) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/conda/proxy][%d] createRepository29Created ", 201)
}

func (o *CreateCondaProxyRepositoryCreated) String() string {
	return fmt.Sprintf("[POST /v1/repositories/conda/proxy][%d] createRepository29Created ", 201)
}

func (o *CreateCondaProxyRepositoryCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateCondaProxyRepositoryUnauthorized creates a CreateCondaProxyRepositoryUnauthorized with default headers values
func NewCreateCondaProxyRepositoryUnauthorized() *CreateCondaProxyRepositoryUnauthorized {
	return &CreateCondaProxyRepositoryUnauthorized{}
}

/*
	CreateCondaProxyRepositoryUnauthorized describes a response with status code 401, with default header values.

Authentication required
*/
type CreateCondaProxyRepositoryUnauthorized struct {
}

// IsSuccess returns true when this create repository29 unauthorized response has a 2xx status code
func (o *CreateCondaProxyRepositoryUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository29 unauthorized response has a 3xx status code
func (o *CreateCondaProxyRepositoryUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository29 unauthorized response has a 4xx status code
func (o *CreateCondaProxyRepositoryUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository29 unauthorized response has a 5xx status code
func (o *CreateCondaProxyRepositoryUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository29 unauthorized response a status code equal to that given
func (o *CreateCondaProxyRepositoryUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *CreateCondaProxyRepositoryUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/conda/proxy][%d] createRepository29Unauthorized ", 401)
}

func (o *CreateCondaProxyRepositoryUnauthorized) String() string {
	return fmt.Sprintf("[POST /v1/repositories/conda/proxy][%d] createRepository29Unauthorized ", 401)
}

func (o *CreateCondaProxyRepositoryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateCondaProxyRepositoryForbidden creates a CreateCondaProxyRepositoryForbidden with default headers values
func NewCreateCondaProxyRepositoryForbidden() *CreateCondaProxyRepositoryForbidden {
	return &CreateCondaProxyRepositoryForbidden{}
}

/*
	CreateCondaProxyRepositoryForbidden describes a response with status code 403, with default header values.

Insufficient permissions
*/
type CreateCondaProxyRepositoryForbidden struct {
}

// IsSuccess returns true when this create repository29 forbidden response has a 2xx status code
func (o *CreateCondaProxyRepositoryForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository29 forbidden response has a 3xx status code
func (o *CreateCondaProxyRepositoryForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository29 forbidden response has a 4xx status code
func (o *CreateCondaProxyRepositoryForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository29 forbidden response has a 5xx status code
func (o *CreateCondaProxyRepositoryForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository29 forbidden response a status code equal to that given
func (o *CreateCondaProxyRepositoryForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *CreateCondaProxyRepositoryForbidden) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/conda/proxy][%d] createRepository29Forbidden ", 403)
}

func (o *CreateCondaProxyRepositoryForbidden) String() string {
	return fmt.Sprintf("[POST /v1/repositories/conda/proxy][%d] createRepository29Forbidden ", 403)
}

func (o *CreateCondaProxyRepositoryForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateCondaProxyRepositoryMethodNotAllowed creates a CreateCondaProxyRepositoryMethodNotAllowed with default headers values
func NewCreateCondaProxyRepositoryMethodNotAllowed() *CreateCondaProxyRepositoryMethodNotAllowed {
	return &CreateCondaProxyRepositoryMethodNotAllowed{}
}

/*
	CreateCondaProxyRepositoryMethodNotAllowed describes a response with status code 405, with default header values.

Feature is disabled in High Availability
*/
type CreateCondaProxyRepositoryMethodNotAllowed struct {
}

// IsSuccess returns true when this create repository29 method not allowed response has a 2xx status code
func (o *CreateCondaProxyRepositoryMethodNotAllowed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository29 method not allowed response has a 3xx status code
func (o *CreateCondaProxyRepositoryMethodNotAllowed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository29 method not allowed response has a 4xx status code
func (o *CreateCondaProxyRepositoryMethodNotAllowed) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository29 method not allowed response has a 5xx status code
func (o *CreateCondaProxyRepositoryMethodNotAllowed) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository29 method not allowed response a status code equal to that given
func (o *CreateCondaProxyRepositoryMethodNotAllowed) IsCode(code int) bool {
	return code == 405
}

func (o *CreateCondaProxyRepositoryMethodNotAllowed) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/conda/proxy][%d] createRepository29MethodNotAllowed ", 405)
}

func (o *CreateCondaProxyRepositoryMethodNotAllowed) String() string {
	return fmt.Sprintf("[POST /v1/repositories/conda/proxy][%d] createRepository29MethodNotAllowed ", 405)
}

func (o *CreateCondaProxyRepositoryMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
