// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Eldarrin/nexus-go-api/models"
)

// NewCreateRHostedRepositoryParams creates a new CreateRHostedRepositoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateRHostedRepositoryParams() *CreateRHostedRepositoryParams {
	return &CreateRHostedRepositoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateRHostedRepositoryParamsWithTimeout creates a new CreateRHostedRepositoryParams object
// with the ability to set a timeout on a request.
func NewCreateRHostedRepositoryParamsWithTimeout(timeout time.Duration) *CreateRHostedRepositoryParams {
	return &CreateRHostedRepositoryParams{
		timeout: timeout,
	}
}

// NewCreateRHostedRepositoryParamsWithContext creates a new CreateRHostedRepositoryParams object
// with the ability to set a context for a request.
func NewCreateRHostedRepositoryParamsWithContext(ctx context.Context) *CreateRHostedRepositoryParams {
	return &CreateRHostedRepositoryParams{
		Context: ctx,
	}
}

// NewCreateRHostedRepositoryParamsWithHTTPClient creates a new CreateRHostedRepositoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateRHostedRepositoryParamsWithHTTPClient(client *http.Client) *CreateRHostedRepositoryParams {
	return &CreateRHostedRepositoryParams{
		HTTPClient: client,
	}
}

/*
CreateRHostedRepositoryParams contains all the parameters to send to the API endpoint

	for the create repository 32 operation.

	Typically these are written to a http.Request.
*/
type CreateRHostedRepositoryParams struct {

	// Body.
	Body *models.RHostedRepositoryAPIRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create repository 32 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateRHostedRepositoryParams) WithDefaults() *CreateRHostedRepositoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create repository 32 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateRHostedRepositoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create repository 32 params
func (o *CreateRHostedRepositoryParams) WithTimeout(timeout time.Duration) *CreateRHostedRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create repository 32 params
func (o *CreateRHostedRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create repository 32 params
func (o *CreateRHostedRepositoryParams) WithContext(ctx context.Context) *CreateRHostedRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create repository 32 params
func (o *CreateRHostedRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create repository 32 params
func (o *CreateRHostedRepositoryParams) WithHTTPClient(client *http.Client) *CreateRHostedRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create repository 32 params
func (o *CreateRHostedRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create repository 32 params
func (o *CreateRHostedRepositoryParams) WithBody(body *models.RHostedRepositoryAPIRequest) *CreateRHostedRepositoryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create repository 32 params
func (o *CreateRHostedRepositoryParams) SetBody(body *models.RHostedRepositoryAPIRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateRHostedRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
