// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Eldarrin/nexus-go-api/models"
)

// NewCreateNpmHostedRepositoryParams creates a new CreateNpmHostedRepositoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateNpmHostedRepositoryParams() *CreateNpmHostedRepositoryParams {
	return &CreateNpmHostedRepositoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateNpmHostedRepositoryParamsWithTimeout creates a new CreateNpmHostedRepositoryParams object
// with the ability to set a timeout on a request.
func NewCreateNpmHostedRepositoryParamsWithTimeout(timeout time.Duration) *CreateNpmHostedRepositoryParams {
	return &CreateNpmHostedRepositoryParams{
		timeout: timeout,
	}
}

// NewCreateNpmHostedRepositoryParamsWithContext creates a new CreateNpmHostedRepositoryParams object
// with the ability to set a context for a request.
func NewCreateNpmHostedRepositoryParamsWithContext(ctx context.Context) *CreateNpmHostedRepositoryParams {
	return &CreateNpmHostedRepositoryParams{
		Context: ctx,
	}
}

// NewCreateNpmHostedRepositoryParamsWithHTTPClient creates a new CreateNpmHostedRepositoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateNpmHostedRepositoryParamsWithHTTPClient(client *http.Client) *CreateNpmHostedRepositoryParams {
	return &CreateNpmHostedRepositoryParams{
		HTTPClient: client,
	}
}

/*
CreateNpmHostedRepositoryParams contains all the parameters to send to the API endpoint

	for the create repository 9 operation.

	Typically these are written to a http.Request.
*/
type CreateNpmHostedRepositoryParams struct {

	// Body.
	Body *models.NpmHostedRepositoryAPIRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create repository 9 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateNpmHostedRepositoryParams) WithDefaults() *CreateNpmHostedRepositoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create repository 9 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateNpmHostedRepositoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create repository 9 params
func (o *CreateNpmHostedRepositoryParams) WithTimeout(timeout time.Duration) *CreateNpmHostedRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create repository 9 params
func (o *CreateNpmHostedRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create repository 9 params
func (o *CreateNpmHostedRepositoryParams) WithContext(ctx context.Context) *CreateNpmHostedRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create repository 9 params
func (o *CreateNpmHostedRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create repository 9 params
func (o *CreateNpmHostedRepositoryParams) WithHTTPClient(client *http.Client) *CreateNpmHostedRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create repository 9 params
func (o *CreateNpmHostedRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create repository 9 params
func (o *CreateNpmHostedRepositoryParams) WithBody(body *models.NpmHostedRepositoryAPIRequest) *CreateNpmHostedRepositoryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create repository 9 params
func (o *CreateNpmHostedRepositoryParams) SetBody(body *models.NpmHostedRepositoryAPIRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateNpmHostedRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
