// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateGolangProxyRepositoryReader is a Reader for the CreateGolangProxyRepository structure.
type CreateGolangProxyRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateGolangProxyRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateGolangProxyRepositoryCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateGolangProxyRepositoryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateGolangProxyRepositoryForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewCreateGolangProxyRepositoryMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateGolangProxyRepositoryCreated creates a CreateGolangProxyRepositoryCreated with default headers values
func NewCreateGolangProxyRepositoryCreated() *CreateGolangProxyRepositoryCreated {
	return &CreateGolangProxyRepositoryCreated{}
}

/*
	CreateGolangProxyRepositoryCreated describes a response with status code 201, with default header values.

Repository created
*/
type CreateGolangProxyRepositoryCreated struct {
}

// IsSuccess returns true when this create repository36 created response has a 2xx status code
func (o *CreateGolangProxyRepositoryCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create repository36 created response has a 3xx status code
func (o *CreateGolangProxyRepositoryCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository36 created response has a 4xx status code
func (o *CreateGolangProxyRepositoryCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create repository36 created response has a 5xx status code
func (o *CreateGolangProxyRepositoryCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository36 created response a status code equal to that given
func (o *CreateGolangProxyRepositoryCreated) IsCode(code int) bool {
	return code == 201
}

func (o *CreateGolangProxyRepositoryCreated) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/go/proxy][%d] createRepository36Created ", 201)
}

func (o *CreateGolangProxyRepositoryCreated) String() string {
	return fmt.Sprintf("[POST /v1/repositories/go/proxy][%d] createRepository36Created ", 201)
}

func (o *CreateGolangProxyRepositoryCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateGolangProxyRepositoryUnauthorized creates a CreateGolangProxyRepositoryUnauthorized with default headers values
func NewCreateGolangProxyRepositoryUnauthorized() *CreateGolangProxyRepositoryUnauthorized {
	return &CreateGolangProxyRepositoryUnauthorized{}
}

/*
	CreateGolangProxyRepositoryUnauthorized describes a response with status code 401, with default header values.

Authentication required
*/
type CreateGolangProxyRepositoryUnauthorized struct {
}

// IsSuccess returns true when this create repository36 unauthorized response has a 2xx status code
func (o *CreateGolangProxyRepositoryUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository36 unauthorized response has a 3xx status code
func (o *CreateGolangProxyRepositoryUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository36 unauthorized response has a 4xx status code
func (o *CreateGolangProxyRepositoryUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository36 unauthorized response has a 5xx status code
func (o *CreateGolangProxyRepositoryUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository36 unauthorized response a status code equal to that given
func (o *CreateGolangProxyRepositoryUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *CreateGolangProxyRepositoryUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/go/proxy][%d] createRepository36Unauthorized ", 401)
}

func (o *CreateGolangProxyRepositoryUnauthorized) String() string {
	return fmt.Sprintf("[POST /v1/repositories/go/proxy][%d] createRepository36Unauthorized ", 401)
}

func (o *CreateGolangProxyRepositoryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateGolangProxyRepositoryForbidden creates a CreateGolangProxyRepositoryForbidden with default headers values
func NewCreateGolangProxyRepositoryForbidden() *CreateGolangProxyRepositoryForbidden {
	return &CreateGolangProxyRepositoryForbidden{}
}

/*
	CreateGolangProxyRepositoryForbidden describes a response with status code 403, with default header values.

Insufficient permissions
*/
type CreateGolangProxyRepositoryForbidden struct {
}

// IsSuccess returns true when this create repository36 forbidden response has a 2xx status code
func (o *CreateGolangProxyRepositoryForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository36 forbidden response has a 3xx status code
func (o *CreateGolangProxyRepositoryForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository36 forbidden response has a 4xx status code
func (o *CreateGolangProxyRepositoryForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository36 forbidden response has a 5xx status code
func (o *CreateGolangProxyRepositoryForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository36 forbidden response a status code equal to that given
func (o *CreateGolangProxyRepositoryForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *CreateGolangProxyRepositoryForbidden) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/go/proxy][%d] createRepository36Forbidden ", 403)
}

func (o *CreateGolangProxyRepositoryForbidden) String() string {
	return fmt.Sprintf("[POST /v1/repositories/go/proxy][%d] createRepository36Forbidden ", 403)
}

func (o *CreateGolangProxyRepositoryForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateGolangProxyRepositoryMethodNotAllowed creates a CreateGolangProxyRepositoryMethodNotAllowed with default headers values
func NewCreateGolangProxyRepositoryMethodNotAllowed() *CreateGolangProxyRepositoryMethodNotAllowed {
	return &CreateGolangProxyRepositoryMethodNotAllowed{}
}

/*
	CreateGolangProxyRepositoryMethodNotAllowed describes a response with status code 405, with default header values.

Feature is disabled in High Availability
*/
type CreateGolangProxyRepositoryMethodNotAllowed struct {
}

// IsSuccess returns true when this create repository36 method not allowed response has a 2xx status code
func (o *CreateGolangProxyRepositoryMethodNotAllowed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository36 method not allowed response has a 3xx status code
func (o *CreateGolangProxyRepositoryMethodNotAllowed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository36 method not allowed response has a 4xx status code
func (o *CreateGolangProxyRepositoryMethodNotAllowed) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository36 method not allowed response has a 5xx status code
func (o *CreateGolangProxyRepositoryMethodNotAllowed) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository36 method not allowed response a status code equal to that given
func (o *CreateGolangProxyRepositoryMethodNotAllowed) IsCode(code int) bool {
	return code == 405
}

func (o *CreateGolangProxyRepositoryMethodNotAllowed) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/go/proxy][%d] createRepository36MethodNotAllowed ", 405)
}

func (o *CreateGolangProxyRepositoryMethodNotAllowed) String() string {
	return fmt.Sprintf("[POST /v1/repositories/go/proxy][%d] createRepository36MethodNotAllowed ", 405)
}

func (o *CreateGolangProxyRepositoryMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
