// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Eldarrin/nexus-go-api/models"
)

// NewCreateP2ProxyRepositoryParams creates a new CreateP2ProxyRepositoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateP2ProxyRepositoryParams() *CreateP2ProxyRepositoryParams {
	return &CreateP2ProxyRepositoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateP2ProxyRepositoryParamsWithTimeout creates a new CreateP2ProxyRepositoryParams object
// with the ability to set a timeout on a request.
func NewCreateP2ProxyRepositoryParamsWithTimeout(timeout time.Duration) *CreateP2ProxyRepositoryParams {
	return &CreateP2ProxyRepositoryParams{
		timeout: timeout,
	}
}

// NewCreateP2ProxyRepositoryParamsWithContext creates a new CreateP2ProxyRepositoryParams object
// with the ability to set a context for a request.
func NewCreateP2ProxyRepositoryParamsWithContext(ctx context.Context) *CreateP2ProxyRepositoryParams {
	return &CreateP2ProxyRepositoryParams{
		Context: ctx,
	}
}

// NewCreateP2ProxyRepositoryParamsWithHTTPClient creates a new CreateP2ProxyRepositoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateP2ProxyRepositoryParamsWithHTTPClient(client *http.Client) *CreateP2ProxyRepositoryParams {
	return &CreateP2ProxyRepositoryParams{
		HTTPClient: client,
	}
}

/*
CreateP2ProxyRepositoryParams contains all the parameters to send to the API endpoint

	for the create repository 37 operation.

	Typically these are written to a http.Request.
*/
type CreateP2ProxyRepositoryParams struct {

	// Body.
	Body *models.P2ProxyRepositoryAPIRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create repository 37 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateP2ProxyRepositoryParams) WithDefaults() *CreateP2ProxyRepositoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create repository 37 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateP2ProxyRepositoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create repository 37 params
func (o *CreateP2ProxyRepositoryParams) WithTimeout(timeout time.Duration) *CreateP2ProxyRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create repository 37 params
func (o *CreateP2ProxyRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create repository 37 params
func (o *CreateP2ProxyRepositoryParams) WithContext(ctx context.Context) *CreateP2ProxyRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create repository 37 params
func (o *CreateP2ProxyRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create repository 37 params
func (o *CreateP2ProxyRepositoryParams) WithHTTPClient(client *http.Client) *CreateP2ProxyRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create repository 37 params
func (o *CreateP2ProxyRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create repository 37 params
func (o *CreateP2ProxyRepositoryParams) WithBody(body *models.P2ProxyRepositoryAPIRequest) *CreateP2ProxyRepositoryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create repository 37 params
func (o *CreateP2ProxyRepositoryParams) SetBody(body *models.P2ProxyRepositoryAPIRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateP2ProxyRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
