// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateDockerHostedRepositoryReader is a Reader for the CreateDockerHostedRepository structure.
type CreateDockerHostedRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateDockerHostedRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateDockerHostedRepositoryCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateDockerHostedRepositoryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateDockerHostedRepositoryForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateDockerHostedRepositoryCreated creates a CreateDockerHostedRepositoryCreated with default headers values
func NewCreateDockerHostedRepositoryCreated() *CreateDockerHostedRepositoryCreated {
	return &CreateDockerHostedRepositoryCreated{}
}

/*
	CreateDockerHostedRepositoryCreated describes a response with status code 201, with default header values.

Repository created
*/
type CreateDockerHostedRepositoryCreated struct {
}

// IsSuccess returns true when this create repository18 created response has a 2xx status code
func (o *CreateDockerHostedRepositoryCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create repository18 created response has a 3xx status code
func (o *CreateDockerHostedRepositoryCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository18 created response has a 4xx status code
func (o *CreateDockerHostedRepositoryCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create repository18 created response has a 5xx status code
func (o *CreateDockerHostedRepositoryCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository18 created response a status code equal to that given
func (o *CreateDockerHostedRepositoryCreated) IsCode(code int) bool {
	return code == 201
}

func (o *CreateDockerHostedRepositoryCreated) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/docker/hosted][%d] createRepository18Created ", 201)
}

func (o *CreateDockerHostedRepositoryCreated) String() string {
	return fmt.Sprintf("[POST /v1/repositories/docker/hosted][%d] createRepository18Created ", 201)
}

func (o *CreateDockerHostedRepositoryCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateDockerHostedRepositoryUnauthorized creates a CreateDockerHostedRepositoryUnauthorized with default headers values
func NewCreateDockerHostedRepositoryUnauthorized() *CreateDockerHostedRepositoryUnauthorized {
	return &CreateDockerHostedRepositoryUnauthorized{}
}

/*
	CreateDockerHostedRepositoryUnauthorized describes a response with status code 401, with default header values.

Authentication required
*/
type CreateDockerHostedRepositoryUnauthorized struct {
}

// IsSuccess returns true when this create repository18 unauthorized response has a 2xx status code
func (o *CreateDockerHostedRepositoryUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository18 unauthorized response has a 3xx status code
func (o *CreateDockerHostedRepositoryUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository18 unauthorized response has a 4xx status code
func (o *CreateDockerHostedRepositoryUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository18 unauthorized response has a 5xx status code
func (o *CreateDockerHostedRepositoryUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository18 unauthorized response a status code equal to that given
func (o *CreateDockerHostedRepositoryUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *CreateDockerHostedRepositoryUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/docker/hosted][%d] createRepository18Unauthorized ", 401)
}

func (o *CreateDockerHostedRepositoryUnauthorized) String() string {
	return fmt.Sprintf("[POST /v1/repositories/docker/hosted][%d] createRepository18Unauthorized ", 401)
}

func (o *CreateDockerHostedRepositoryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateDockerHostedRepositoryForbidden creates a CreateDockerHostedRepositoryForbidden with default headers values
func NewCreateDockerHostedRepositoryForbidden() *CreateDockerHostedRepositoryForbidden {
	return &CreateDockerHostedRepositoryForbidden{}
}

/*
	CreateDockerHostedRepositoryForbidden describes a response with status code 403, with default header values.

Repository not found
*/
type CreateDockerHostedRepositoryForbidden struct {
}

// IsSuccess returns true when this create repository18 forbidden response has a 2xx status code
func (o *CreateDockerHostedRepositoryForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository18 forbidden response has a 3xx status code
func (o *CreateDockerHostedRepositoryForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository18 forbidden response has a 4xx status code
func (o *CreateDockerHostedRepositoryForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository18 forbidden response has a 5xx status code
func (o *CreateDockerHostedRepositoryForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository18 forbidden response a status code equal to that given
func (o *CreateDockerHostedRepositoryForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *CreateDockerHostedRepositoryForbidden) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/docker/hosted][%d] createRepository18Forbidden ", 403)
}

func (o *CreateDockerHostedRepositoryForbidden) String() string {
	return fmt.Sprintf("[POST /v1/repositories/docker/hosted][%d] createRepository18Forbidden ", 403)
}

func (o *CreateDockerHostedRepositoryForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
