// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Eldarrin/nexus-go-api/models"
)

// NewCreateBowerGroupRepositoryParams creates a new CreateBowerGroupRepositoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateBowerGroupRepositoryParams() *CreateBowerGroupRepositoryParams {
	return &CreateBowerGroupRepositoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateBowerGroupRepositoryParamsWithTimeout creates a new CreateBowerGroupRepositoryParams object
// with the ability to set a timeout on a request.
func NewCreateBowerGroupRepositoryParamsWithTimeout(timeout time.Duration) *CreateBowerGroupRepositoryParams {
	return &CreateBowerGroupRepositoryParams{
		timeout: timeout,
	}
}

// NewCreateBowerGroupRepositoryParamsWithContext creates a new CreateBowerGroupRepositoryParams object
// with the ability to set a context for a request.
func NewCreateBowerGroupRepositoryParamsWithContext(ctx context.Context) *CreateBowerGroupRepositoryParams {
	return &CreateBowerGroupRepositoryParams{
		Context: ctx,
	}
}

// NewCreateBowerGroupRepositoryParamsWithHTTPClient creates a new CreateBowerGroupRepositoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateBowerGroupRepositoryParamsWithHTTPClient(client *http.Client) *CreateBowerGroupRepositoryParams {
	return &CreateBowerGroupRepositoryParams{
		HTTPClient: client,
	}
}

/*
CreateBowerGroupRepositoryParams contains all the parameters to send to the API endpoint

	for the create repository 38 operation.

	Typically these are written to a http.Request.
*/
type CreateBowerGroupRepositoryParams struct {

	// Body.
	Body *models.BowerGroupRepositoryAPIRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create repository 38 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateBowerGroupRepositoryParams) WithDefaults() *CreateBowerGroupRepositoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create repository 38 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateBowerGroupRepositoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create repository 38 params
func (o *CreateBowerGroupRepositoryParams) WithTimeout(timeout time.Duration) *CreateBowerGroupRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create repository 38 params
func (o *CreateBowerGroupRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create repository 38 params
func (o *CreateBowerGroupRepositoryParams) WithContext(ctx context.Context) *CreateBowerGroupRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create repository 38 params
func (o *CreateBowerGroupRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create repository 38 params
func (o *CreateBowerGroupRepositoryParams) WithHTTPClient(client *http.Client) *CreateBowerGroupRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create repository 38 params
func (o *CreateBowerGroupRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create repository 38 params
func (o *CreateBowerGroupRepositoryParams) WithBody(body *models.BowerGroupRepositoryAPIRequest) *CreateBowerGroupRepositoryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create repository 38 params
func (o *CreateBowerGroupRepositoryParams) SetBody(body *models.BowerGroupRepositoryAPIRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateBowerGroupRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
