// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Eldarrin/nexus-go-api/models"
)

// NewCreateHelmHostedRepositoryParams creates a new CreateHelmHostedRepositoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateHelmHostedRepositoryParams() *CreateHelmHostedRepositoryParams {
	return &CreateHelmHostedRepositoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateHelmHostedRepositoryParamsWithTimeout creates a new CreateHelmHostedRepositoryParams object
// with the ability to set a timeout on a request.
func NewCreateHelmHostedRepositoryParamsWithTimeout(timeout time.Duration) *CreateHelmHostedRepositoryParams {
	return &CreateHelmHostedRepositoryParams{
		timeout: timeout,
	}
}

// NewCreateHelmHostedRepositoryParamsWithContext creates a new CreateHelmHostedRepositoryParams object
// with the ability to set a context for a request.
func NewCreateHelmHostedRepositoryParamsWithContext(ctx context.Context) *CreateHelmHostedRepositoryParams {
	return &CreateHelmHostedRepositoryParams{
		Context: ctx,
	}
}

// NewCreateHelmHostedRepositoryParamsWithHTTPClient creates a new CreateHelmHostedRepositoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateHelmHostedRepositoryParamsWithHTTPClient(client *http.Client) *CreateHelmHostedRepositoryParams {
	return &CreateHelmHostedRepositoryParams{
		HTTPClient: client,
	}
}

/*
CreateHelmHostedRepositoryParams contains all the parameters to send to the API endpoint

	for the create repository 23 operation.

	Typically these are written to a http.Request.
*/
type CreateHelmHostedRepositoryParams struct {

	// Body.
	Body *models.HelmHostedRepositoryAPIRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create repository 23 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateHelmHostedRepositoryParams) WithDefaults() *CreateHelmHostedRepositoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create repository 23 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateHelmHostedRepositoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create repository 23 params
func (o *CreateHelmHostedRepositoryParams) WithTimeout(timeout time.Duration) *CreateHelmHostedRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create repository 23 params
func (o *CreateHelmHostedRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create repository 23 params
func (o *CreateHelmHostedRepositoryParams) WithContext(ctx context.Context) *CreateHelmHostedRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create repository 23 params
func (o *CreateHelmHostedRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create repository 23 params
func (o *CreateHelmHostedRepositoryParams) WithHTTPClient(client *http.Client) *CreateHelmHostedRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create repository 23 params
func (o *CreateHelmHostedRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create repository 23 params
func (o *CreateHelmHostedRepositoryParams) WithBody(body *models.HelmHostedRepositoryAPIRequest) *CreateHelmHostedRepositoryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create repository 23 params
func (o *CreateHelmHostedRepositoryParams) SetBody(body *models.HelmHostedRepositoryAPIRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateHelmHostedRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
