// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateBowerHostedRepositoryReader is a Reader for the CreateBowerHostedRepository structure.
type CreateBowerHostedRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateBowerHostedRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateBowerHostedRepositoryCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateBowerHostedRepositoryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateBowerHostedRepositoryForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateBowerHostedRepositoryCreated creates a CreateBowerHostedRepositoryCreated with default headers values
func NewCreateBowerHostedRepositoryCreated() *CreateBowerHostedRepositoryCreated {
	return &CreateBowerHostedRepositoryCreated{}
}

/*
	CreateBowerHostedRepositoryCreated describes a response with status code 201, with default header values.

Repository created
*/
type CreateBowerHostedRepositoryCreated struct {
}

// IsSuccess returns true when this create repository39 created response has a 2xx status code
func (o *CreateBowerHostedRepositoryCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create repository39 created response has a 3xx status code
func (o *CreateBowerHostedRepositoryCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository39 created response has a 4xx status code
func (o *CreateBowerHostedRepositoryCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create repository39 created response has a 5xx status code
func (o *CreateBowerHostedRepositoryCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository39 created response a status code equal to that given
func (o *CreateBowerHostedRepositoryCreated) IsCode(code int) bool {
	return code == 201
}

func (o *CreateBowerHostedRepositoryCreated) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/bower/hosted][%d] createRepository39Created ", 201)
}

func (o *CreateBowerHostedRepositoryCreated) String() string {
	return fmt.Sprintf("[POST /v1/repositories/bower/hosted][%d] createRepository39Created ", 201)
}

func (o *CreateBowerHostedRepositoryCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateBowerHostedRepositoryUnauthorized creates a CreateBowerHostedRepositoryUnauthorized with default headers values
func NewCreateBowerHostedRepositoryUnauthorized() *CreateBowerHostedRepositoryUnauthorized {
	return &CreateBowerHostedRepositoryUnauthorized{}
}

/*
	CreateBowerHostedRepositoryUnauthorized describes a response with status code 401, with default header values.

Authentication required
*/
type CreateBowerHostedRepositoryUnauthorized struct {
}

// IsSuccess returns true when this create repository39 unauthorized response has a 2xx status code
func (o *CreateBowerHostedRepositoryUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository39 unauthorized response has a 3xx status code
func (o *CreateBowerHostedRepositoryUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository39 unauthorized response has a 4xx status code
func (o *CreateBowerHostedRepositoryUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository39 unauthorized response has a 5xx status code
func (o *CreateBowerHostedRepositoryUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository39 unauthorized response a status code equal to that given
func (o *CreateBowerHostedRepositoryUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *CreateBowerHostedRepositoryUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/bower/hosted][%d] createRepository39Unauthorized ", 401)
}

func (o *CreateBowerHostedRepositoryUnauthorized) String() string {
	return fmt.Sprintf("[POST /v1/repositories/bower/hosted][%d] createRepository39Unauthorized ", 401)
}

func (o *CreateBowerHostedRepositoryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateBowerHostedRepositoryForbidden creates a CreateBowerHostedRepositoryForbidden with default headers values
func NewCreateBowerHostedRepositoryForbidden() *CreateBowerHostedRepositoryForbidden {
	return &CreateBowerHostedRepositoryForbidden{}
}

/*
	CreateBowerHostedRepositoryForbidden describes a response with status code 403, with default header values.

Insufficient permissions
*/
type CreateBowerHostedRepositoryForbidden struct {
}

// IsSuccess returns true when this create repository39 forbidden response has a 2xx status code
func (o *CreateBowerHostedRepositoryForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository39 forbidden response has a 3xx status code
func (o *CreateBowerHostedRepositoryForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository39 forbidden response has a 4xx status code
func (o *CreateBowerHostedRepositoryForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository39 forbidden response has a 5xx status code
func (o *CreateBowerHostedRepositoryForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository39 forbidden response a status code equal to that given
func (o *CreateBowerHostedRepositoryForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *CreateBowerHostedRepositoryForbidden) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/bower/hosted][%d] createRepository39Forbidden ", 403)
}

func (o *CreateBowerHostedRepositoryForbidden) String() string {
	return fmt.Sprintf("[POST /v1/repositories/bower/hosted][%d] createRepository39Forbidden ", 403)
}

func (o *CreateBowerHostedRepositoryForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
