// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateGolangGroupRepositoryReader is a Reader for the CreateGolangGroupRepository structure.
type CreateGolangGroupRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateGolangGroupRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateGolangGroupRepositoryCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateGolangGroupRepositoryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateGolangGroupRepositoryForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewCreateGolangGroupRepositoryMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateGolangGroupRepositoryCreated creates a CreateGolangGroupRepositoryCreated with default headers values
func NewCreateGolangGroupRepositoryCreated() *CreateGolangGroupRepositoryCreated {
	return &CreateGolangGroupRepositoryCreated{}
}

/*
	CreateGolangGroupRepositoryCreated describes a response with status code 201, with default header values.

Repository created
*/
type CreateGolangGroupRepositoryCreated struct {
}

// IsSuccess returns true when this create repository35 created response has a 2xx status code
func (o *CreateGolangGroupRepositoryCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create repository35 created response has a 3xx status code
func (o *CreateGolangGroupRepositoryCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository35 created response has a 4xx status code
func (o *CreateGolangGroupRepositoryCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create repository35 created response has a 5xx status code
func (o *CreateGolangGroupRepositoryCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository35 created response a status code equal to that given
func (o *CreateGolangGroupRepositoryCreated) IsCode(code int) bool {
	return code == 201
}

func (o *CreateGolangGroupRepositoryCreated) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/go/group][%d] createRepository35Created ", 201)
}

func (o *CreateGolangGroupRepositoryCreated) String() string {
	return fmt.Sprintf("[POST /v1/repositories/go/group][%d] createRepository35Created ", 201)
}

func (o *CreateGolangGroupRepositoryCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateGolangGroupRepositoryUnauthorized creates a CreateGolangGroupRepositoryUnauthorized with default headers values
func NewCreateGolangGroupRepositoryUnauthorized() *CreateGolangGroupRepositoryUnauthorized {
	return &CreateGolangGroupRepositoryUnauthorized{}
}

/*
	CreateGolangGroupRepositoryUnauthorized describes a response with status code 401, with default header values.

Authentication required
*/
type CreateGolangGroupRepositoryUnauthorized struct {
}

// IsSuccess returns true when this create repository35 unauthorized response has a 2xx status code
func (o *CreateGolangGroupRepositoryUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository35 unauthorized response has a 3xx status code
func (o *CreateGolangGroupRepositoryUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository35 unauthorized response has a 4xx status code
func (o *CreateGolangGroupRepositoryUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository35 unauthorized response has a 5xx status code
func (o *CreateGolangGroupRepositoryUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository35 unauthorized response a status code equal to that given
func (o *CreateGolangGroupRepositoryUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *CreateGolangGroupRepositoryUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/go/group][%d] createRepository35Unauthorized ", 401)
}

func (o *CreateGolangGroupRepositoryUnauthorized) String() string {
	return fmt.Sprintf("[POST /v1/repositories/go/group][%d] createRepository35Unauthorized ", 401)
}

func (o *CreateGolangGroupRepositoryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateGolangGroupRepositoryForbidden creates a CreateGolangGroupRepositoryForbidden with default headers values
func NewCreateGolangGroupRepositoryForbidden() *CreateGolangGroupRepositoryForbidden {
	return &CreateGolangGroupRepositoryForbidden{}
}

/*
	CreateGolangGroupRepositoryForbidden describes a response with status code 403, with default header values.

Insufficient permissions
*/
type CreateGolangGroupRepositoryForbidden struct {
}

// IsSuccess returns true when this create repository35 forbidden response has a 2xx status code
func (o *CreateGolangGroupRepositoryForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository35 forbidden response has a 3xx status code
func (o *CreateGolangGroupRepositoryForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository35 forbidden response has a 4xx status code
func (o *CreateGolangGroupRepositoryForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository35 forbidden response has a 5xx status code
func (o *CreateGolangGroupRepositoryForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository35 forbidden response a status code equal to that given
func (o *CreateGolangGroupRepositoryForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *CreateGolangGroupRepositoryForbidden) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/go/group][%d] createRepository35Forbidden ", 403)
}

func (o *CreateGolangGroupRepositoryForbidden) String() string {
	return fmt.Sprintf("[POST /v1/repositories/go/group][%d] createRepository35Forbidden ", 403)
}

func (o *CreateGolangGroupRepositoryForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateGolangGroupRepositoryMethodNotAllowed creates a CreateGolangGroupRepositoryMethodNotAllowed with default headers values
func NewCreateGolangGroupRepositoryMethodNotAllowed() *CreateGolangGroupRepositoryMethodNotAllowed {
	return &CreateGolangGroupRepositoryMethodNotAllowed{}
}

/*
	CreateGolangGroupRepositoryMethodNotAllowed describes a response with status code 405, with default header values.

Feature is disabled in High Availability
*/
type CreateGolangGroupRepositoryMethodNotAllowed struct {
}

// IsSuccess returns true when this create repository35 method not allowed response has a 2xx status code
func (o *CreateGolangGroupRepositoryMethodNotAllowed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository35 method not allowed response has a 3xx status code
func (o *CreateGolangGroupRepositoryMethodNotAllowed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository35 method not allowed response has a 4xx status code
func (o *CreateGolangGroupRepositoryMethodNotAllowed) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository35 method not allowed response has a 5xx status code
func (o *CreateGolangGroupRepositoryMethodNotAllowed) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository35 method not allowed response a status code equal to that given
func (o *CreateGolangGroupRepositoryMethodNotAllowed) IsCode(code int) bool {
	return code == 405
}

func (o *CreateGolangGroupRepositoryMethodNotAllowed) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/go/group][%d] createRepository35MethodNotAllowed ", 405)
}

func (o *CreateGolangGroupRepositoryMethodNotAllowed) String() string {
	return fmt.Sprintf("[POST /v1/repositories/go/group][%d] createRepository35MethodNotAllowed ", 405)
}

func (o *CreateGolangGroupRepositoryMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
