// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateDockerGroupRepositoryReader is a Reader for the CreateDockerGroupRepository structure.
type CreateDockerGroupRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateDockerGroupRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateDockerGroupRepositoryCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateDockerGroupRepositoryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateDockerGroupRepositoryForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateDockerGroupRepositoryCreated creates a CreateDockerGroupRepositoryCreated with default headers values
func NewCreateDockerGroupRepositoryCreated() *CreateDockerGroupRepositoryCreated {
	return &CreateDockerGroupRepositoryCreated{}
}

/*
	CreateDockerGroupRepositoryCreated describes a response with status code 201, with default header values.

Repository created
*/
type CreateDockerGroupRepositoryCreated struct {
}

// IsSuccess returns true when this create repository17 created response has a 2xx status code
func (o *CreateDockerGroupRepositoryCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create repository17 created response has a 3xx status code
func (o *CreateDockerGroupRepositoryCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository17 created response has a 4xx status code
func (o *CreateDockerGroupRepositoryCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create repository17 created response has a 5xx status code
func (o *CreateDockerGroupRepositoryCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository17 created response a status code equal to that given
func (o *CreateDockerGroupRepositoryCreated) IsCode(code int) bool {
	return code == 201
}

func (o *CreateDockerGroupRepositoryCreated) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/docker/group][%d] createRepository17Created ", 201)
}

func (o *CreateDockerGroupRepositoryCreated) String() string {
	return fmt.Sprintf("[POST /v1/repositories/docker/group][%d] createRepository17Created ", 201)
}

func (o *CreateDockerGroupRepositoryCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateDockerGroupRepositoryUnauthorized creates a CreateDockerGroupRepositoryUnauthorized with default headers values
func NewCreateDockerGroupRepositoryUnauthorized() *CreateDockerGroupRepositoryUnauthorized {
	return &CreateDockerGroupRepositoryUnauthorized{}
}

/*
	CreateDockerGroupRepositoryUnauthorized describes a response with status code 401, with default header values.

Authentication required
*/
type CreateDockerGroupRepositoryUnauthorized struct {
}

// IsSuccess returns true when this create repository17 unauthorized response has a 2xx status code
func (o *CreateDockerGroupRepositoryUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository17 unauthorized response has a 3xx status code
func (o *CreateDockerGroupRepositoryUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository17 unauthorized response has a 4xx status code
func (o *CreateDockerGroupRepositoryUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository17 unauthorized response has a 5xx status code
func (o *CreateDockerGroupRepositoryUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository17 unauthorized response a status code equal to that given
func (o *CreateDockerGroupRepositoryUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *CreateDockerGroupRepositoryUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/docker/group][%d] createRepository17Unauthorized ", 401)
}

func (o *CreateDockerGroupRepositoryUnauthorized) String() string {
	return fmt.Sprintf("[POST /v1/repositories/docker/group][%d] createRepository17Unauthorized ", 401)
}

func (o *CreateDockerGroupRepositoryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateDockerGroupRepositoryForbidden creates a CreateDockerGroupRepositoryForbidden with default headers values
func NewCreateDockerGroupRepositoryForbidden() *CreateDockerGroupRepositoryForbidden {
	return &CreateDockerGroupRepositoryForbidden{}
}

/*
	CreateDockerGroupRepositoryForbidden describes a response with status code 403, with default header values.

Insufficient permissions
*/
type CreateDockerGroupRepositoryForbidden struct {
}

// IsSuccess returns true when this create repository17 forbidden response has a 2xx status code
func (o *CreateDockerGroupRepositoryForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository17 forbidden response has a 3xx status code
func (o *CreateDockerGroupRepositoryForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository17 forbidden response has a 4xx status code
func (o *CreateDockerGroupRepositoryForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository17 forbidden response has a 5xx status code
func (o *CreateDockerGroupRepositoryForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository17 forbidden response a status code equal to that given
func (o *CreateDockerGroupRepositoryForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *CreateDockerGroupRepositoryForbidden) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/docker/group][%d] createRepository17Forbidden ", 403)
}

func (o *CreateDockerGroupRepositoryForbidden) String() string {
	return fmt.Sprintf("[POST /v1/repositories/docker/group][%d] createRepository17Forbidden ", 403)
}

func (o *CreateDockerGroupRepositoryForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
