// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateRProxyRepositoryReader is a Reader for the CreateRProxyRepository structure.
type CreateRProxyRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateRProxyRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateRProxyRepositoryCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateRProxyRepositoryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateRProxyRepositoryForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewCreateRProxyRepositoryMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateRProxyRepositoryCreated creates a CreateRProxyRepositoryCreated with default headers values
func NewCreateRProxyRepositoryCreated() *CreateRProxyRepositoryCreated {
	return &CreateRProxyRepositoryCreated{}
}

/*
	CreateRProxyRepositoryCreated describes a response with status code 201, with default header values.

Repository created
*/
type CreateRProxyRepositoryCreated struct {
}

// IsSuccess returns true when this create repository33 created response has a 2xx status code
func (o *CreateRProxyRepositoryCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create repository33 created response has a 3xx status code
func (o *CreateRProxyRepositoryCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository33 created response has a 4xx status code
func (o *CreateRProxyRepositoryCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create repository33 created response has a 5xx status code
func (o *CreateRProxyRepositoryCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository33 created response a status code equal to that given
func (o *CreateRProxyRepositoryCreated) IsCode(code int) bool {
	return code == 201
}

func (o *CreateRProxyRepositoryCreated) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/r/proxy][%d] createRepository33Created ", 201)
}

func (o *CreateRProxyRepositoryCreated) String() string {
	return fmt.Sprintf("[POST /v1/repositories/r/proxy][%d] createRepository33Created ", 201)
}

func (o *CreateRProxyRepositoryCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateRProxyRepositoryUnauthorized creates a CreateRProxyRepositoryUnauthorized with default headers values
func NewCreateRProxyRepositoryUnauthorized() *CreateRProxyRepositoryUnauthorized {
	return &CreateRProxyRepositoryUnauthorized{}
}

/*
	CreateRProxyRepositoryUnauthorized describes a response with status code 401, with default header values.

Authentication required
*/
type CreateRProxyRepositoryUnauthorized struct {
}

// IsSuccess returns true when this create repository33 unauthorized response has a 2xx status code
func (o *CreateRProxyRepositoryUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository33 unauthorized response has a 3xx status code
func (o *CreateRProxyRepositoryUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository33 unauthorized response has a 4xx status code
func (o *CreateRProxyRepositoryUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository33 unauthorized response has a 5xx status code
func (o *CreateRProxyRepositoryUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository33 unauthorized response a status code equal to that given
func (o *CreateRProxyRepositoryUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *CreateRProxyRepositoryUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/r/proxy][%d] createRepository33Unauthorized ", 401)
}

func (o *CreateRProxyRepositoryUnauthorized) String() string {
	return fmt.Sprintf("[POST /v1/repositories/r/proxy][%d] createRepository33Unauthorized ", 401)
}

func (o *CreateRProxyRepositoryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateRProxyRepositoryForbidden creates a CreateRProxyRepositoryForbidden with default headers values
func NewCreateRProxyRepositoryForbidden() *CreateRProxyRepositoryForbidden {
	return &CreateRProxyRepositoryForbidden{}
}

/*
	CreateRProxyRepositoryForbidden describes a response with status code 403, with default header values.

Insufficient permissions
*/
type CreateRProxyRepositoryForbidden struct {
}

// IsSuccess returns true when this create repository33 forbidden response has a 2xx status code
func (o *CreateRProxyRepositoryForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository33 forbidden response has a 3xx status code
func (o *CreateRProxyRepositoryForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository33 forbidden response has a 4xx status code
func (o *CreateRProxyRepositoryForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository33 forbidden response has a 5xx status code
func (o *CreateRProxyRepositoryForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository33 forbidden response a status code equal to that given
func (o *CreateRProxyRepositoryForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *CreateRProxyRepositoryForbidden) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/r/proxy][%d] createRepository33Forbidden ", 403)
}

func (o *CreateRProxyRepositoryForbidden) String() string {
	return fmt.Sprintf("[POST /v1/repositories/r/proxy][%d] createRepository33Forbidden ", 403)
}

func (o *CreateRProxyRepositoryForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateRProxyRepositoryMethodNotAllowed creates a CreateRProxyRepositoryMethodNotAllowed with default headers values
func NewCreateRProxyRepositoryMethodNotAllowed() *CreateRProxyRepositoryMethodNotAllowed {
	return &CreateRProxyRepositoryMethodNotAllowed{}
}

/*
	CreateRProxyRepositoryMethodNotAllowed describes a response with status code 405, with default header values.

Feature is disabled in High Availability
*/
type CreateRProxyRepositoryMethodNotAllowed struct {
}

// IsSuccess returns true when this create repository33 method not allowed response has a 2xx status code
func (o *CreateRProxyRepositoryMethodNotAllowed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository33 method not allowed response has a 3xx status code
func (o *CreateRProxyRepositoryMethodNotAllowed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository33 method not allowed response has a 4xx status code
func (o *CreateRProxyRepositoryMethodNotAllowed) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository33 method not allowed response has a 5xx status code
func (o *CreateRProxyRepositoryMethodNotAllowed) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository33 method not allowed response a status code equal to that given
func (o *CreateRProxyRepositoryMethodNotAllowed) IsCode(code int) bool {
	return code == 405
}

func (o *CreateRProxyRepositoryMethodNotAllowed) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/r/proxy][%d] createRepository33MethodNotAllowed ", 405)
}

func (o *CreateRProxyRepositoryMethodNotAllowed) String() string {
	return fmt.Sprintf("[POST /v1/repositories/r/proxy][%d] createRepository33MethodNotAllowed ", 405)
}

func (o *CreateRProxyRepositoryMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
