// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Eldarrin/nexus-go-api/models"
)

// NewCreateMavenGroupRepositoryParams creates a new CreateMavenGroupRepositoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateMavenGroupRepositoryParams() *CreateMavenGroupRepositoryParams {
	return &CreateMavenGroupRepositoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateMavenGroupRepositoryParamsWithTimeout creates a new CreateMavenGroupRepositoryParams object
// with the ability to set a timeout on a request.
func NewCreateMavenGroupRepositoryParamsWithTimeout(timeout time.Duration) *CreateMavenGroupRepositoryParams {
	return &CreateMavenGroupRepositoryParams{
		timeout: timeout,
	}
}

// NewCreateMavenGroupRepositoryParamsWithContext creates a new CreateMavenGroupRepositoryParams object
// with the ability to set a context for a request.
func NewCreateMavenGroupRepositoryParamsWithContext(ctx context.Context) *CreateMavenGroupRepositoryParams {
	return &CreateMavenGroupRepositoryParams{
		Context: ctx,
	}
}

// NewCreateMavenGroupRepositoryParamsWithHTTPClient creates a new CreateMavenGroupRepositoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateMavenGroupRepositoryParamsWithHTTPClient(client *http.Client) *CreateMavenGroupRepositoryParams {
	return &CreateMavenGroupRepositoryParams{
		HTTPClient: client,
	}
}

/*
CreateMavenGroupRepositoryParams contains all the parameters to send to the API endpoint

	for the create repository operation.

	Typically these are written to a http.Request.
*/
type CreateMavenGroupRepositoryParams struct {

	// Body.
	Body *models.MavenGroupRepositoryAPIRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create repository params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateMavenGroupRepositoryParams) WithDefaults() *CreateMavenGroupRepositoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create repository params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateMavenGroupRepositoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create repository params
func (o *CreateMavenGroupRepositoryParams) WithTimeout(timeout time.Duration) *CreateMavenGroupRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create repository params
func (o *CreateMavenGroupRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create repository params
func (o *CreateMavenGroupRepositoryParams) WithContext(ctx context.Context) *CreateMavenGroupRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create repository params
func (o *CreateMavenGroupRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create repository params
func (o *CreateMavenGroupRepositoryParams) WithHTTPClient(client *http.Client) *CreateMavenGroupRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create repository params
func (o *CreateMavenGroupRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create repository params
func (o *CreateMavenGroupRepositoryParams) WithBody(body *models.MavenGroupRepositoryAPIRequest) *CreateMavenGroupRepositoryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create repository params
func (o *CreateMavenGroupRepositoryParams) SetBody(body *models.MavenGroupRepositoryAPIRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateMavenGroupRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
