// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateGitLfsHostedRepositoryReader is a Reader for the CreateGitLfsHostedRepository structure.
type CreateGitLfsHostedRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateGitLfsHostedRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateGitLfsHostedRepositoryCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateGitLfsHostedRepositoryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateGitLfsHostedRepositoryForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateGitLfsHostedRepositoryCreated creates a CreateGitLfsHostedRepositoryCreated with default headers values
func NewCreateGitLfsHostedRepositoryCreated() *CreateGitLfsHostedRepositoryCreated {
	return &CreateGitLfsHostedRepositoryCreated{}
}

/*
	CreateGitLfsHostedRepositoryCreated describes a response with status code 201, with default header values.

Repository created
*/
type CreateGitLfsHostedRepositoryCreated struct {
}

// IsSuccess returns true when this create repository25 created response has a 2xx status code
func (o *CreateGitLfsHostedRepositoryCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create repository25 created response has a 3xx status code
func (o *CreateGitLfsHostedRepositoryCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository25 created response has a 4xx status code
func (o *CreateGitLfsHostedRepositoryCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create repository25 created response has a 5xx status code
func (o *CreateGitLfsHostedRepositoryCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository25 created response a status code equal to that given
func (o *CreateGitLfsHostedRepositoryCreated) IsCode(code int) bool {
	return code == 201
}

func (o *CreateGitLfsHostedRepositoryCreated) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/gitlfs/hosted][%d] createRepository25Created ", 201)
}

func (o *CreateGitLfsHostedRepositoryCreated) String() string {
	return fmt.Sprintf("[POST /v1/repositories/gitlfs/hosted][%d] createRepository25Created ", 201)
}

func (o *CreateGitLfsHostedRepositoryCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateGitLfsHostedRepositoryUnauthorized creates a CreateGitLfsHostedRepositoryUnauthorized with default headers values
func NewCreateGitLfsHostedRepositoryUnauthorized() *CreateGitLfsHostedRepositoryUnauthorized {
	return &CreateGitLfsHostedRepositoryUnauthorized{}
}

/*
	CreateGitLfsHostedRepositoryUnauthorized describes a response with status code 401, with default header values.

Authentication required
*/
type CreateGitLfsHostedRepositoryUnauthorized struct {
}

// IsSuccess returns true when this create repository25 unauthorized response has a 2xx status code
func (o *CreateGitLfsHostedRepositoryUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository25 unauthorized response has a 3xx status code
func (o *CreateGitLfsHostedRepositoryUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository25 unauthorized response has a 4xx status code
func (o *CreateGitLfsHostedRepositoryUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository25 unauthorized response has a 5xx status code
func (o *CreateGitLfsHostedRepositoryUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository25 unauthorized response a status code equal to that given
func (o *CreateGitLfsHostedRepositoryUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *CreateGitLfsHostedRepositoryUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/gitlfs/hosted][%d] createRepository25Unauthorized ", 401)
}

func (o *CreateGitLfsHostedRepositoryUnauthorized) String() string {
	return fmt.Sprintf("[POST /v1/repositories/gitlfs/hosted][%d] createRepository25Unauthorized ", 401)
}

func (o *CreateGitLfsHostedRepositoryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateGitLfsHostedRepositoryForbidden creates a CreateGitLfsHostedRepositoryForbidden with default headers values
func NewCreateGitLfsHostedRepositoryForbidden() *CreateGitLfsHostedRepositoryForbidden {
	return &CreateGitLfsHostedRepositoryForbidden{}
}

/*
	CreateGitLfsHostedRepositoryForbidden describes a response with status code 403, with default header values.

Insufficient permissions
*/
type CreateGitLfsHostedRepositoryForbidden struct {
}

// IsSuccess returns true when this create repository25 forbidden response has a 2xx status code
func (o *CreateGitLfsHostedRepositoryForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository25 forbidden response has a 3xx status code
func (o *CreateGitLfsHostedRepositoryForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository25 forbidden response has a 4xx status code
func (o *CreateGitLfsHostedRepositoryForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository25 forbidden response has a 5xx status code
func (o *CreateGitLfsHostedRepositoryForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository25 forbidden response a status code equal to that given
func (o *CreateGitLfsHostedRepositoryForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *CreateGitLfsHostedRepositoryForbidden) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/gitlfs/hosted][%d] createRepository25Forbidden ", 403)
}

func (o *CreateGitLfsHostedRepositoryForbidden) String() string {
	return fmt.Sprintf("[POST /v1/repositories/gitlfs/hosted][%d] createRepository25Forbidden ", 403)
}

func (o *CreateGitLfsHostedRepositoryForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
