// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Eldarrin/nexus-go-api/models"
)

// NewCreatePypiGroupRepositoryParams creates a new CreatePypiGroupRepositoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreatePypiGroupRepositoryParams() *CreatePypiGroupRepositoryParams {
	return &CreatePypiGroupRepositoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreatePypiGroupRepositoryParamsWithTimeout creates a new CreatePypiGroupRepositoryParams object
// with the ability to set a timeout on a request.
func NewCreatePypiGroupRepositoryParamsWithTimeout(timeout time.Duration) *CreatePypiGroupRepositoryParams {
	return &CreatePypiGroupRepositoryParams{
		timeout: timeout,
	}
}

// NewCreatePypiGroupRepositoryParamsWithContext creates a new CreatePypiGroupRepositoryParams object
// with the ability to set a context for a request.
func NewCreatePypiGroupRepositoryParamsWithContext(ctx context.Context) *CreatePypiGroupRepositoryParams {
	return &CreatePypiGroupRepositoryParams{
		Context: ctx,
	}
}

// NewCreatePypiGroupRepositoryParamsWithHTTPClient creates a new CreatePypiGroupRepositoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreatePypiGroupRepositoryParamsWithHTTPClient(client *http.Client) *CreatePypiGroupRepositoryParams {
	return &CreatePypiGroupRepositoryParams{
		HTTPClient: client,
	}
}

/*
CreatePypiGroupRepositoryParams contains all the parameters to send to the API endpoint

	for the create repository 26 operation.

	Typically these are written to a http.Request.
*/
type CreatePypiGroupRepositoryParams struct {

	// Body.
	Body *models.PypiGroupRepositoryAPIRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create repository 26 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreatePypiGroupRepositoryParams) WithDefaults() *CreatePypiGroupRepositoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create repository 26 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreatePypiGroupRepositoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create repository 26 params
func (o *CreatePypiGroupRepositoryParams) WithTimeout(timeout time.Duration) *CreatePypiGroupRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create repository 26 params
func (o *CreatePypiGroupRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create repository 26 params
func (o *CreatePypiGroupRepositoryParams) WithContext(ctx context.Context) *CreatePypiGroupRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create repository 26 params
func (o *CreatePypiGroupRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create repository 26 params
func (o *CreatePypiGroupRepositoryParams) WithHTTPClient(client *http.Client) *CreatePypiGroupRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create repository 26 params
func (o *CreatePypiGroupRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create repository 26 params
func (o *CreatePypiGroupRepositoryParams) WithBody(body *models.PypiGroupRepositoryAPIRequest) *CreatePypiGroupRepositoryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create repository 26 params
func (o *CreatePypiGroupRepositoryParams) SetBody(body *models.PypiGroupRepositoryAPIRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreatePypiGroupRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
