// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Eldarrin/nexus-go-api/models"
)

// NewCreateRubyGemsHostedRepositoryParams creates a new CreateRubyGemsHostedRepositoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateRubyGemsHostedRepositoryParams() *CreateRubyGemsHostedRepositoryParams {
	return &CreateRubyGemsHostedRepositoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateRubyGemsHostedRepositoryParamsWithTimeout creates a new CreateRubyGemsHostedRepositoryParams object
// with the ability to set a timeout on a request.
func NewCreateRubyGemsHostedRepositoryParamsWithTimeout(timeout time.Duration) *CreateRubyGemsHostedRepositoryParams {
	return &CreateRubyGemsHostedRepositoryParams{
		timeout: timeout,
	}
}

// NewCreateRubyGemsHostedRepositoryParamsWithContext creates a new CreateRubyGemsHostedRepositoryParams object
// with the ability to set a context for a request.
func NewCreateRubyGemsHostedRepositoryParamsWithContext(ctx context.Context) *CreateRubyGemsHostedRepositoryParams {
	return &CreateRubyGemsHostedRepositoryParams{
		Context: ctx,
	}
}

// NewCreateRubyGemsHostedRepositoryParamsWithHTTPClient creates a new CreateRubyGemsHostedRepositoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateRubyGemsHostedRepositoryParamsWithHTTPClient(client *http.Client) *CreateRubyGemsHostedRepositoryParams {
	return &CreateRubyGemsHostedRepositoryParams{
		HTTPClient: client,
	}
}

/*
CreateRubyGemsHostedRepositoryParams contains all the parameters to send to the API endpoint

	for the create repository 15 operation.

	Typically these are written to a http.Request.
*/
type CreateRubyGemsHostedRepositoryParams struct {

	// Body.
	Body *models.RubyGemsHostedRepositoryAPIRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create repository 15 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateRubyGemsHostedRepositoryParams) WithDefaults() *CreateRubyGemsHostedRepositoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create repository 15 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateRubyGemsHostedRepositoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create repository 15 params
func (o *CreateRubyGemsHostedRepositoryParams) WithTimeout(timeout time.Duration) *CreateRubyGemsHostedRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create repository 15 params
func (o *CreateRubyGemsHostedRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create repository 15 params
func (o *CreateRubyGemsHostedRepositoryParams) WithContext(ctx context.Context) *CreateRubyGemsHostedRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create repository 15 params
func (o *CreateRubyGemsHostedRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create repository 15 params
func (o *CreateRubyGemsHostedRepositoryParams) WithHTTPClient(client *http.Client) *CreateRubyGemsHostedRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create repository 15 params
func (o *CreateRubyGemsHostedRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create repository 15 params
func (o *CreateRubyGemsHostedRepositoryParams) WithBody(body *models.RubyGemsHostedRepositoryAPIRequest) *CreateRubyGemsHostedRepositoryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create repository 15 params
func (o *CreateRubyGemsHostedRepositoryParams) SetBody(body *models.RubyGemsHostedRepositoryAPIRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateRubyGemsHostedRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
