// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Eldarrin/nexus-go-api/models"
)

// NewCreateAptProxyRepositoryParams creates a new CreateAptProxyRepositoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateAptProxyRepositoryParams() *CreateAptProxyRepositoryParams {
	return &CreateAptProxyRepositoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateAptProxyRepositoryParamsWithTimeout creates a new CreateAptProxyRepositoryParams object
// with the ability to set a timeout on a request.
func NewCreateAptProxyRepositoryParamsWithTimeout(timeout time.Duration) *CreateAptProxyRepositoryParams {
	return &CreateAptProxyRepositoryParams{
		timeout: timeout,
	}
}

// NewCreateAptProxyRepositoryParamsWithContext creates a new CreateAptProxyRepositoryParams object
// with the ability to set a context for a request.
func NewCreateAptProxyRepositoryParamsWithContext(ctx context.Context) *CreateAptProxyRepositoryParams {
	return &CreateAptProxyRepositoryParams{
		Context: ctx,
	}
}

// NewCreateAptProxyRepositoryParamsWithHTTPClient creates a new CreateAptProxyRepositoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateAptProxyRepositoryParamsWithHTTPClient(client *http.Client) *CreateAptProxyRepositoryParams {
	return &CreateAptProxyRepositoryParams{
		HTTPClient: client,
	}
}

/*
CreateAptProxyRepositoryParams contains all the parameters to send to the API endpoint

	for the create repository 4 operation.

	Typically these are written to a http.Request.
*/
type CreateAptProxyRepositoryParams struct {

	// Body.
	Body *models.AptProxyRepositoryAPIRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create repository 4 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateAptProxyRepositoryParams) WithDefaults() *CreateAptProxyRepositoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create repository 4 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateAptProxyRepositoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create repository 4 params
func (o *CreateAptProxyRepositoryParams) WithTimeout(timeout time.Duration) *CreateAptProxyRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create repository 4 params
func (o *CreateAptProxyRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create repository 4 params
func (o *CreateAptProxyRepositoryParams) WithContext(ctx context.Context) *CreateAptProxyRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create repository 4 params
func (o *CreateAptProxyRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create repository 4 params
func (o *CreateAptProxyRepositoryParams) WithHTTPClient(client *http.Client) *CreateAptProxyRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create repository 4 params
func (o *CreateAptProxyRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create repository 4 params
func (o *CreateAptProxyRepositoryParams) WithBody(body *models.AptProxyRepositoryAPIRequest) *CreateAptProxyRepositoryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create repository 4 params
func (o *CreateAptProxyRepositoryParams) SetBody(body *models.AptProxyRepositoryAPIRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateAptProxyRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
