// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateNpmGroupRepositoryReader is a Reader for the CreateNpmGroupRepository structure.
type CreateNpmGroupRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateNpmGroupRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateNpmGroupRepositoryCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateNpmGroupRepositoryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateNpmGroupRepositoryForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateNpmGroupRepositoryCreated creates a CreateNpmGroupRepositoryCreated with default headers values
func NewCreateNpmGroupRepositoryCreated() *CreateNpmGroupRepositoryCreated {
	return &CreateNpmGroupRepositoryCreated{}
}

/*
	CreateNpmGroupRepositoryCreated describes a response with status code 201, with default header values.

Repository created
*/
type CreateNpmGroupRepositoryCreated struct {
}

// IsSuccess returns true when this create repository8 created response has a 2xx status code
func (o *CreateNpmGroupRepositoryCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create repository8 created response has a 3xx status code
func (o *CreateNpmGroupRepositoryCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository8 created response has a 4xx status code
func (o *CreateNpmGroupRepositoryCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create repository8 created response has a 5xx status code
func (o *CreateNpmGroupRepositoryCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository8 created response a status code equal to that given
func (o *CreateNpmGroupRepositoryCreated) IsCode(code int) bool {
	return code == 201
}

func (o *CreateNpmGroupRepositoryCreated) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/npm/group][%d] createRepository8Created ", 201)
}

func (o *CreateNpmGroupRepositoryCreated) String() string {
	return fmt.Sprintf("[POST /v1/repositories/npm/group][%d] createRepository8Created ", 201)
}

func (o *CreateNpmGroupRepositoryCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateNpmGroupRepositoryUnauthorized creates a CreateNpmGroupRepositoryUnauthorized with default headers values
func NewCreateNpmGroupRepositoryUnauthorized() *CreateNpmGroupRepositoryUnauthorized {
	return &CreateNpmGroupRepositoryUnauthorized{}
}

/*
	CreateNpmGroupRepositoryUnauthorized describes a response with status code 401, with default header values.

Authentication required
*/
type CreateNpmGroupRepositoryUnauthorized struct {
}

// IsSuccess returns true when this create repository8 unauthorized response has a 2xx status code
func (o *CreateNpmGroupRepositoryUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository8 unauthorized response has a 3xx status code
func (o *CreateNpmGroupRepositoryUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository8 unauthorized response has a 4xx status code
func (o *CreateNpmGroupRepositoryUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository8 unauthorized response has a 5xx status code
func (o *CreateNpmGroupRepositoryUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository8 unauthorized response a status code equal to that given
func (o *CreateNpmGroupRepositoryUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *CreateNpmGroupRepositoryUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/npm/group][%d] createRepository8Unauthorized ", 401)
}

func (o *CreateNpmGroupRepositoryUnauthorized) String() string {
	return fmt.Sprintf("[POST /v1/repositories/npm/group][%d] createRepository8Unauthorized ", 401)
}

func (o *CreateNpmGroupRepositoryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateNpmGroupRepositoryForbidden creates a CreateNpmGroupRepositoryForbidden with default headers values
func NewCreateNpmGroupRepositoryForbidden() *CreateNpmGroupRepositoryForbidden {
	return &CreateNpmGroupRepositoryForbidden{}
}

/*
	CreateNpmGroupRepositoryForbidden describes a response with status code 403, with default header values.

Insufficient permissions
*/
type CreateNpmGroupRepositoryForbidden struct {
}

// IsSuccess returns true when this create repository8 forbidden response has a 2xx status code
func (o *CreateNpmGroupRepositoryForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository8 forbidden response has a 3xx status code
func (o *CreateNpmGroupRepositoryForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository8 forbidden response has a 4xx status code
func (o *CreateNpmGroupRepositoryForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository8 forbidden response has a 5xx status code
func (o *CreateNpmGroupRepositoryForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository8 forbidden response a status code equal to that given
func (o *CreateNpmGroupRepositoryForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *CreateNpmGroupRepositoryForbidden) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/npm/group][%d] createRepository8Forbidden ", 403)
}

func (o *CreateNpmGroupRepositoryForbidden) String() string {
	return fmt.Sprintf("[POST /v1/repositories/npm/group][%d] createRepository8Forbidden ", 403)
}

func (o *CreateNpmGroupRepositoryForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
