// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateYumHostedRepositoryReader is a Reader for the CreateYumHostedRepository structure.
type CreateYumHostedRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateYumHostedRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateYumHostedRepositoryCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateYumHostedRepositoryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateYumHostedRepositoryForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateYumHostedRepositoryCreated creates a CreateYumHostedRepositoryCreated with default headers values
func NewCreateYumHostedRepositoryCreated() *CreateYumHostedRepositoryCreated {
	return &CreateYumHostedRepositoryCreated{}
}

/*
	CreateYumHostedRepositoryCreated describes a response with status code 201, with default header values.

Repository created
*/
type CreateYumHostedRepositoryCreated struct {
}

// IsSuccess returns true when this create repository21 created response has a 2xx status code
func (o *CreateYumHostedRepositoryCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create repository21 created response has a 3xx status code
func (o *CreateYumHostedRepositoryCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository21 created response has a 4xx status code
func (o *CreateYumHostedRepositoryCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create repository21 created response has a 5xx status code
func (o *CreateYumHostedRepositoryCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository21 created response a status code equal to that given
func (o *CreateYumHostedRepositoryCreated) IsCode(code int) bool {
	return code == 201
}

func (o *CreateYumHostedRepositoryCreated) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/yum/hosted][%d] createRepository21Created ", 201)
}

func (o *CreateYumHostedRepositoryCreated) String() string {
	return fmt.Sprintf("[POST /v1/repositories/yum/hosted][%d] createRepository21Created ", 201)
}

func (o *CreateYumHostedRepositoryCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateYumHostedRepositoryUnauthorized creates a CreateYumHostedRepositoryUnauthorized with default headers values
func NewCreateYumHostedRepositoryUnauthorized() *CreateYumHostedRepositoryUnauthorized {
	return &CreateYumHostedRepositoryUnauthorized{}
}

/*
	CreateYumHostedRepositoryUnauthorized describes a response with status code 401, with default header values.

Authentication required
*/
type CreateYumHostedRepositoryUnauthorized struct {
}

// IsSuccess returns true when this create repository21 unauthorized response has a 2xx status code
func (o *CreateYumHostedRepositoryUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository21 unauthorized response has a 3xx status code
func (o *CreateYumHostedRepositoryUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository21 unauthorized response has a 4xx status code
func (o *CreateYumHostedRepositoryUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository21 unauthorized response has a 5xx status code
func (o *CreateYumHostedRepositoryUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository21 unauthorized response a status code equal to that given
func (o *CreateYumHostedRepositoryUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *CreateYumHostedRepositoryUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/yum/hosted][%d] createRepository21Unauthorized ", 401)
}

func (o *CreateYumHostedRepositoryUnauthorized) String() string {
	return fmt.Sprintf("[POST /v1/repositories/yum/hosted][%d] createRepository21Unauthorized ", 401)
}

func (o *CreateYumHostedRepositoryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateYumHostedRepositoryForbidden creates a CreateYumHostedRepositoryForbidden with default headers values
func NewCreateYumHostedRepositoryForbidden() *CreateYumHostedRepositoryForbidden {
	return &CreateYumHostedRepositoryForbidden{}
}

/*
	CreateYumHostedRepositoryForbidden describes a response with status code 403, with default header values.

Insufficient permissions
*/
type CreateYumHostedRepositoryForbidden struct {
}

// IsSuccess returns true when this create repository21 forbidden response has a 2xx status code
func (o *CreateYumHostedRepositoryForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository21 forbidden response has a 3xx status code
func (o *CreateYumHostedRepositoryForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository21 forbidden response has a 4xx status code
func (o *CreateYumHostedRepositoryForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository21 forbidden response has a 5xx status code
func (o *CreateYumHostedRepositoryForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository21 forbidden response a status code equal to that given
func (o *CreateYumHostedRepositoryForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *CreateYumHostedRepositoryForbidden) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/yum/hosted][%d] createRepository21Forbidden ", 403)
}

func (o *CreateYumHostedRepositoryForbidden) String() string {
	return fmt.Sprintf("[POST /v1/repositories/yum/hosted][%d] createRepository21Forbidden ", 403)
}

func (o *CreateYumHostedRepositoryForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
