// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRubyGemsHostedRepositoryParams creates a new GetRubyGemsHostedRepositoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRubyGemsHostedRepositoryParams() *GetRubyGemsHostedRepositoryParams {
	return &GetRubyGemsHostedRepositoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRubyGemsHostedRepositoryParamsWithTimeout creates a new GetRubyGemsHostedRepositoryParams object
// with the ability to set a timeout on a request.
func NewGetRubyGemsHostedRepositoryParamsWithTimeout(timeout time.Duration) *GetRubyGemsHostedRepositoryParams {
	return &GetRubyGemsHostedRepositoryParams{
		timeout: timeout,
	}
}

// NewGetRubyGemsHostedRepositoryParamsWithContext creates a new GetRubyGemsHostedRepositoryParams object
// with the ability to set a context for a request.
func NewGetRubyGemsHostedRepositoryParamsWithContext(ctx context.Context) *GetRubyGemsHostedRepositoryParams {
	return &GetRubyGemsHostedRepositoryParams{
		Context: ctx,
	}
}

// NewGetRubyGemsHostedRepositoryParamsWithHTTPClient creates a new GetRubyGemsHostedRepositoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRubyGemsHostedRepositoryParamsWithHTTPClient(client *http.Client) *GetRubyGemsHostedRepositoryParams {
	return &GetRubyGemsHostedRepositoryParams{
		HTTPClient: client,
	}
}

/*
GetRubyGemsHostedRepositoryParams contains all the parameters to send to the API endpoint

	for the get repository 16 operation.

	Typically these are written to a http.Request.
*/
type GetRubyGemsHostedRepositoryParams struct {

	// RepositoryName.
	RepositoryName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get repository 16 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRubyGemsHostedRepositoryParams) WithDefaults() *GetRubyGemsHostedRepositoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get repository 16 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRubyGemsHostedRepositoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get repository 16 params
func (o *GetRubyGemsHostedRepositoryParams) WithTimeout(timeout time.Duration) *GetRubyGemsHostedRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get repository 16 params
func (o *GetRubyGemsHostedRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get repository 16 params
func (o *GetRubyGemsHostedRepositoryParams) WithContext(ctx context.Context) *GetRubyGemsHostedRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get repository 16 params
func (o *GetRubyGemsHostedRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get repository 16 params
func (o *GetRubyGemsHostedRepositoryParams) WithHTTPClient(client *http.Client) *GetRubyGemsHostedRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get repository 16 params
func (o *GetRubyGemsHostedRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRepositoryName adds the repositoryName to the get repository 16 params
func (o *GetRubyGemsHostedRepositoryParams) WithRepositoryName(repositoryName string) *GetRubyGemsHostedRepositoryParams {
	o.SetRepositoryName(repositoryName)
	return o
}

// SetRepositoryName adds the repositoryName to the get repository 16 params
func (o *GetRubyGemsHostedRepositoryParams) SetRepositoryName(repositoryName string) {
	o.RepositoryName = repositoryName
}

// WriteToRequest writes these params to a swagger request
func (o *GetRubyGemsHostedRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param repositoryName
	if err := r.SetPathParam("repositoryName", o.RepositoryName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
