// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMavenGroupRepositoryParams creates a new GetMavenGroupRepositoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMavenGroupRepositoryParams() *GetMavenGroupRepositoryParams {
	return &GetMavenGroupRepositoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMavenGroupRepositoryParamsWithTimeout creates a new GetMavenGroupRepositoryParams object
// with the ability to set a timeout on a request.
func NewGetMavenGroupRepositoryParamsWithTimeout(timeout time.Duration) *GetMavenGroupRepositoryParams {
	return &GetMavenGroupRepositoryParams{
		timeout: timeout,
	}
}

// NewGetMavenGroupRepositoryParamsWithContext creates a new GetMavenGroupRepositoryParams object
// with the ability to set a context for a request.
func NewGetMavenGroupRepositoryParamsWithContext(ctx context.Context) *GetMavenGroupRepositoryParams {
	return &GetMavenGroupRepositoryParams{
		Context: ctx,
	}
}

// NewGetMavenGroupRepositoryParamsWithHTTPClient creates a new GetMavenGroupRepositoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMavenGroupRepositoryParamsWithHTTPClient(client *http.Client) *GetMavenGroupRepositoryParams {
	return &GetMavenGroupRepositoryParams{
		HTTPClient: client,
	}
}

/*
GetMavenGroupRepositoryParams contains all the parameters to send to the API endpoint

	for the get repository 1 operation.

	Typically these are written to a http.Request.
*/
type GetMavenGroupRepositoryParams struct {

	// RepositoryName.
	RepositoryName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get repository 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMavenGroupRepositoryParams) WithDefaults() *GetMavenGroupRepositoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get repository 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMavenGroupRepositoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get repository 1 params
func (o *GetMavenGroupRepositoryParams) WithTimeout(timeout time.Duration) *GetMavenGroupRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get repository 1 params
func (o *GetMavenGroupRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get repository 1 params
func (o *GetMavenGroupRepositoryParams) WithContext(ctx context.Context) *GetMavenGroupRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get repository 1 params
func (o *GetMavenGroupRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get repository 1 params
func (o *GetMavenGroupRepositoryParams) WithHTTPClient(client *http.Client) *GetMavenGroupRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get repository 1 params
func (o *GetMavenGroupRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRepositoryName adds the repositoryName to the get repository 1 params
func (o *GetMavenGroupRepositoryParams) WithRepositoryName(repositoryName string) *GetMavenGroupRepositoryParams {
	o.SetRepositoryName(repositoryName)
	return o
}

// SetRepositoryName adds the repositoryName to the get repository 1 params
func (o *GetMavenGroupRepositoryParams) SetRepositoryName(repositoryName string) {
	o.RepositoryName = repositoryName
}

// WriteToRequest writes these params to a swagger request
func (o *GetMavenGroupRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param repositoryName
	if err := r.SetPathParam("repositoryName", o.RepositoryName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
