// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Eldarrin/nexus-go-api/models"
)

// GetP2ProxyRepositoryReader is a Reader for the GetP2ProxyRepository structure.
type GetP2ProxyRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetP2ProxyRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetP2ProxyRepositoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetP2ProxyRepositoryOK creates a GetP2ProxyRepositoryOK with default headers values
func NewGetP2ProxyRepositoryOK() *GetP2ProxyRepositoryOK {
	return &GetP2ProxyRepositoryOK{}
}

/*
	GetP2ProxyRepositoryOK describes a response with status code 200, with default header values.

successful operation
*/
type GetP2ProxyRepositoryOK struct {
	Payload *models.SimpleAPIProxyRepository
}

// IsSuccess returns true when this get repository38 o k response has a 2xx status code
func (o *GetP2ProxyRepositoryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get repository38 o k response has a 3xx status code
func (o *GetP2ProxyRepositoryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get repository38 o k response has a 4xx status code
func (o *GetP2ProxyRepositoryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get repository38 o k response has a 5xx status code
func (o *GetP2ProxyRepositoryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get repository38 o k response a status code equal to that given
func (o *GetP2ProxyRepositoryOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetP2ProxyRepositoryOK) Error() string {
	return fmt.Sprintf("[GET /v1/repositories/p2/proxy/{repositoryName}][%d] getRepository38OK  %+v", 200, o.Payload)
}

func (o *GetP2ProxyRepositoryOK) String() string {
	return fmt.Sprintf("[GET /v1/repositories/p2/proxy/{repositoryName}][%d] getRepository38OK  %+v", 200, o.Payload)
}

func (o *GetP2ProxyRepositoryOK) GetPayload() *models.SimpleAPIProxyRepository {
	return o.Payload
}

func (o *GetP2ProxyRepositoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SimpleAPIProxyRepository)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
