// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Eldarrin/nexus-go-api/models"
)

// GetNugetProxyRepositoryReader is a Reader for the GetNugetProxyRepository structure.
type GetNugetProxyRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNugetProxyRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNugetProxyRepositoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetNugetProxyRepositoryOK creates a GetNugetProxyRepositoryOK with default headers values
func NewGetNugetProxyRepositoryOK() *GetNugetProxyRepositoryOK {
	return &GetNugetProxyRepositoryOK{}
}

/*
	GetNugetProxyRepositoryOK describes a response with status code 200, with default header values.

successful operation
*/
type GetNugetProxyRepositoryOK struct {
	Payload *models.NugetProxyAPIRepository
}

// IsSuccess returns true when this get repository14 o k response has a 2xx status code
func (o *GetNugetProxyRepositoryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get repository14 o k response has a 3xx status code
func (o *GetNugetProxyRepositoryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get repository14 o k response has a 4xx status code
func (o *GetNugetProxyRepositoryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get repository14 o k response has a 5xx status code
func (o *GetNugetProxyRepositoryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get repository14 o k response a status code equal to that given
func (o *GetNugetProxyRepositoryOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetNugetProxyRepositoryOK) Error() string {
	return fmt.Sprintf("[GET /v1/repositories/nuget/proxy/{repositoryName}][%d] getRepository14OK  %+v", 200, o.Payload)
}

func (o *GetNugetProxyRepositoryOK) String() string {
	return fmt.Sprintf("[GET /v1/repositories/nuget/proxy/{repositoryName}][%d] getRepository14OK  %+v", 200, o.Payload)
}

func (o *GetNugetProxyRepositoryOK) GetPayload() *models.NugetProxyAPIRepository {
	return o.Payload
}

func (o *GetNugetProxyRepositoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NugetProxyAPIRepository)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
