// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Eldarrin/nexus-go-api/models"
)

// GetAptHostedRepositoryReader is a Reader for the GetAptHostedRepository structure.
type GetAptHostedRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAptHostedRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAptHostedRepositoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAptHostedRepositoryOK creates a GetAptHostedRepositoryOK with default headers values
func NewGetAptHostedRepositoryOK() *GetAptHostedRepositoryOK {
	return &GetAptHostedRepositoryOK{}
}

/*
	GetAptHostedRepositoryOK describes a response with status code 200, with default header values.

successful operation
*/
type GetAptHostedRepositoryOK struct {
	Payload *models.AptHostedAPIRepository
}

// IsSuccess returns true when this get repository4 o k response has a 2xx status code
func (o *GetAptHostedRepositoryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get repository4 o k response has a 3xx status code
func (o *GetAptHostedRepositoryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get repository4 o k response has a 4xx status code
func (o *GetAptHostedRepositoryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get repository4 o k response has a 5xx status code
func (o *GetAptHostedRepositoryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get repository4 o k response a status code equal to that given
func (o *GetAptHostedRepositoryOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetAptHostedRepositoryOK) Error() string {
	return fmt.Sprintf("[GET /v1/repositories/apt/hosted/{repositoryName}][%d] getRepository4OK  %+v", 200, o.Payload)
}

func (o *GetAptHostedRepositoryOK) String() string {
	return fmt.Sprintf("[GET /v1/repositories/apt/hosted/{repositoryName}][%d] getRepository4OK  %+v", 200, o.Payload)
}

func (o *GetAptHostedRepositoryOK) GetPayload() *models.AptHostedAPIRepository {
	return o.Payload
}

func (o *GetAptHostedRepositoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AptHostedAPIRepository)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
