// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRawProxyRepositoryParams creates a new GetRawProxyRepositoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRawProxyRepositoryParams() *GetRawProxyRepositoryParams {
	return &GetRawProxyRepositoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRawProxyRepositoryParamsWithTimeout creates a new GetRawProxyRepositoryParams object
// with the ability to set a timeout on a request.
func NewGetRawProxyRepositoryParamsWithTimeout(timeout time.Duration) *GetRawProxyRepositoryParams {
	return &GetRawProxyRepositoryParams{
		timeout: timeout,
	}
}

// NewGetRawProxyRepositoryParamsWithContext creates a new GetRawProxyRepositoryParams object
// with the ability to set a context for a request.
func NewGetRawProxyRepositoryParamsWithContext(ctx context.Context) *GetRawProxyRepositoryParams {
	return &GetRawProxyRepositoryParams{
		Context: ctx,
	}
}

// NewGetRawProxyRepositoryParamsWithHTTPClient creates a new GetRawProxyRepositoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRawProxyRepositoryParamsWithHTTPClient(client *http.Client) *GetRawProxyRepositoryParams {
	return &GetRawProxyRepositoryParams{
		HTTPClient: client,
	}
}

/*
GetRawProxyRepositoryParams contains all the parameters to send to the API endpoint

	for the get repository 8 operation.

	Typically these are written to a http.Request.
*/
type GetRawProxyRepositoryParams struct {

	// RepositoryName.
	RepositoryName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get repository 8 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRawProxyRepositoryParams) WithDefaults() *GetRawProxyRepositoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get repository 8 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRawProxyRepositoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get repository 8 params
func (o *GetRawProxyRepositoryParams) WithTimeout(timeout time.Duration) *GetRawProxyRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get repository 8 params
func (o *GetRawProxyRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get repository 8 params
func (o *GetRawProxyRepositoryParams) WithContext(ctx context.Context) *GetRawProxyRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get repository 8 params
func (o *GetRawProxyRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get repository 8 params
func (o *GetRawProxyRepositoryParams) WithHTTPClient(client *http.Client) *GetRawProxyRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get repository 8 params
func (o *GetRawProxyRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRepositoryName adds the repositoryName to the get repository 8 params
func (o *GetRawProxyRepositoryParams) WithRepositoryName(repositoryName string) *GetRawProxyRepositoryParams {
	o.SetRepositoryName(repositoryName)
	return o
}

// SetRepositoryName adds the repositoryName to the get repository 8 params
func (o *GetRawProxyRepositoryParams) SetRepositoryName(repositoryName string) {
	o.RepositoryName = repositoryName
}

// WriteToRequest writes these params to a swagger request
func (o *GetRawProxyRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param repositoryName
	if err := r.SetPathParam("repositoryName", o.RepositoryName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
