// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Eldarrin/nexus-go-api/models"
)

// GetPypiGroupRepositoryReader is a Reader for the GetPypiGroupRepository structure.
type GetPypiGroupRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPypiGroupRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPypiGroupRepositoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPypiGroupRepositoryOK creates a GetPypiGroupRepositoryOK with default headers values
func NewGetPypiGroupRepositoryOK() *GetPypiGroupRepositoryOK {
	return &GetPypiGroupRepositoryOK{}
}

/*
	GetPypiGroupRepositoryOK describes a response with status code 200, with default header values.

successful operation
*/
type GetPypiGroupRepositoryOK struct {
	Payload *models.SimpleAPIGroupRepository
}

// IsSuccess returns true when this get repository27 o k response has a 2xx status code
func (o *GetPypiGroupRepositoryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get repository27 o k response has a 3xx status code
func (o *GetPypiGroupRepositoryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get repository27 o k response has a 4xx status code
func (o *GetPypiGroupRepositoryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get repository27 o k response has a 5xx status code
func (o *GetPypiGroupRepositoryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get repository27 o k response a status code equal to that given
func (o *GetPypiGroupRepositoryOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetPypiGroupRepositoryOK) Error() string {
	return fmt.Sprintf("[GET /v1/repositories/pypi/group/{repositoryName}][%d] getRepository27OK  %+v", 200, o.Payload)
}

func (o *GetPypiGroupRepositoryOK) String() string {
	return fmt.Sprintf("[GET /v1/repositories/pypi/group/{repositoryName}][%d] getRepository27OK  %+v", 200, o.Payload)
}

func (o *GetPypiGroupRepositoryOK) GetPayload() *models.SimpleAPIGroupRepository {
	return o.Payload
}

func (o *GetPypiGroupRepositoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SimpleAPIGroupRepository)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
