// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetNugetGroupRepositoryParams creates a new GetNugetGroupRepositoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetNugetGroupRepositoryParams() *GetNugetGroupRepositoryParams {
	return &GetNugetGroupRepositoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetNugetGroupRepositoryParamsWithTimeout creates a new GetNugetGroupRepositoryParams object
// with the ability to set a timeout on a request.
func NewGetNugetGroupRepositoryParamsWithTimeout(timeout time.Duration) *GetNugetGroupRepositoryParams {
	return &GetNugetGroupRepositoryParams{
		timeout: timeout,
	}
}

// NewGetNugetGroupRepositoryParamsWithContext creates a new GetNugetGroupRepositoryParams object
// with the ability to set a context for a request.
func NewGetNugetGroupRepositoryParamsWithContext(ctx context.Context) *GetNugetGroupRepositoryParams {
	return &GetNugetGroupRepositoryParams{
		Context: ctx,
	}
}

// NewGetNugetGroupRepositoryParamsWithHTTPClient creates a new GetNugetGroupRepositoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetNugetGroupRepositoryParamsWithHTTPClient(client *http.Client) *GetNugetGroupRepositoryParams {
	return &GetNugetGroupRepositoryParams{
		HTTPClient: client,
	}
}

/*
GetNugetGroupRepositoryParams contains all the parameters to send to the API endpoint

	for the get repository 12 operation.

	Typically these are written to a http.Request.
*/
type GetNugetGroupRepositoryParams struct {

	// RepositoryName.
	RepositoryName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get repository 12 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNugetGroupRepositoryParams) WithDefaults() *GetNugetGroupRepositoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get repository 12 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNugetGroupRepositoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get repository 12 params
func (o *GetNugetGroupRepositoryParams) WithTimeout(timeout time.Duration) *GetNugetGroupRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get repository 12 params
func (o *GetNugetGroupRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get repository 12 params
func (o *GetNugetGroupRepositoryParams) WithContext(ctx context.Context) *GetNugetGroupRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get repository 12 params
func (o *GetNugetGroupRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get repository 12 params
func (o *GetNugetGroupRepositoryParams) WithHTTPClient(client *http.Client) *GetNugetGroupRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get repository 12 params
func (o *GetNugetGroupRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRepositoryName adds the repositoryName to the get repository 12 params
func (o *GetNugetGroupRepositoryParams) WithRepositoryName(repositoryName string) *GetNugetGroupRepositoryParams {
	o.SetRepositoryName(repositoryName)
	return o
}

// SetRepositoryName adds the repositoryName to the get repository 12 params
func (o *GetNugetGroupRepositoryParams) SetRepositoryName(repositoryName string) {
	o.RepositoryName = repositoryName
}

// WriteToRequest writes these params to a swagger request
func (o *GetNugetGroupRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param repositoryName
	if err := r.SetPathParam("repositoryName", o.RepositoryName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
