// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Eldarrin/nexus-go-api/models"
)

// GetBowerGroupRepositoryReader is a Reader for the GetBowerGroupRepository structure.
type GetBowerGroupRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBowerGroupRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBowerGroupRepositoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetBowerGroupRepositoryOK creates a GetBowerGroupRepositoryOK with default headers values
func NewGetBowerGroupRepositoryOK() *GetBowerGroupRepositoryOK {
	return &GetBowerGroupRepositoryOK{}
}

/*
	GetBowerGroupRepositoryOK describes a response with status code 200, with default header values.

successful operation
*/
type GetBowerGroupRepositoryOK struct {
	Payload *models.SimpleAPIGroupRepository
}

// IsSuccess returns true when this get repository39 o k response has a 2xx status code
func (o *GetBowerGroupRepositoryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get repository39 o k response has a 3xx status code
func (o *GetBowerGroupRepositoryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get repository39 o k response has a 4xx status code
func (o *GetBowerGroupRepositoryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get repository39 o k response has a 5xx status code
func (o *GetBowerGroupRepositoryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get repository39 o k response a status code equal to that given
func (o *GetBowerGroupRepositoryOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetBowerGroupRepositoryOK) Error() string {
	return fmt.Sprintf("[GET /v1/repositories/bower/group/{repositoryName}][%d] getRepository39OK  %+v", 200, o.Payload)
}

func (o *GetBowerGroupRepositoryOK) String() string {
	return fmt.Sprintf("[GET /v1/repositories/bower/group/{repositoryName}][%d] getRepository39OK  %+v", 200, o.Payload)
}

func (o *GetBowerGroupRepositoryOK) GetPayload() *models.SimpleAPIGroupRepository {
	return o.Payload
}

func (o *GetBowerGroupRepositoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SimpleAPIGroupRepository)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
