// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Eldarrin/nexus-go-api/models"
)

// GetBowerHostedRepositoryReader is a Reader for the GetBowerHostedRepository structure.
type GetBowerHostedRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBowerHostedRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBowerHostedRepositoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetBowerHostedRepositoryOK creates a GetBowerHostedRepositoryOK with default headers values
func NewGetBowerHostedRepositoryOK() *GetBowerHostedRepositoryOK {
	return &GetBowerHostedRepositoryOK{}
}

/*
	GetBowerHostedRepositoryOK describes a response with status code 200, with default header values.

successful operation
*/
type GetBowerHostedRepositoryOK struct {
	Payload *models.SimpleAPIHostedRepository
}

// IsSuccess returns true when this get repository40 o k response has a 2xx status code
func (o *GetBowerHostedRepositoryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get repository40 o k response has a 3xx status code
func (o *GetBowerHostedRepositoryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get repository40 o k response has a 4xx status code
func (o *GetBowerHostedRepositoryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get repository40 o k response has a 5xx status code
func (o *GetBowerHostedRepositoryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get repository40 o k response a status code equal to that given
func (o *GetBowerHostedRepositoryOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetBowerHostedRepositoryOK) Error() string {
	return fmt.Sprintf("[GET /v1/repositories/bower/hosted/{repositoryName}][%d] getRepository40OK  %+v", 200, o.Payload)
}

func (o *GetBowerHostedRepositoryOK) String() string {
	return fmt.Sprintf("[GET /v1/repositories/bower/hosted/{repositoryName}][%d] getRepository40OK  %+v", 200, o.Payload)
}

func (o *GetBowerHostedRepositoryOK) GetPayload() *models.SimpleAPIHostedRepository {
	return o.Payload
}

func (o *GetBowerHostedRepositoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SimpleAPIHostedRepository)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
