// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateMavenHostedRepositoryReader is a Reader for the UpdateMavenHostedRepository structure.
type UpdateMavenHostedRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateMavenHostedRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUpdateMavenHostedRepositoryNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewUpdateMavenHostedRepositoryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateMavenHostedRepositoryForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateMavenHostedRepositoryNoContent creates a UpdateMavenHostedRepositoryNoContent with default headers values
func NewUpdateMavenHostedRepositoryNoContent() *UpdateMavenHostedRepositoryNoContent {
	return &UpdateMavenHostedRepositoryNoContent{}
}

/*
	UpdateMavenHostedRepositoryNoContent describes a response with status code 204, with default header values.

Repository updated
*/
type UpdateMavenHostedRepositoryNoContent struct {
}

// IsSuccess returns true when this update repository1 no content response has a 2xx status code
func (o *UpdateMavenHostedRepositoryNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update repository1 no content response has a 3xx status code
func (o *UpdateMavenHostedRepositoryNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update repository1 no content response has a 4xx status code
func (o *UpdateMavenHostedRepositoryNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this update repository1 no content response has a 5xx status code
func (o *UpdateMavenHostedRepositoryNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this update repository1 no content response a status code equal to that given
func (o *UpdateMavenHostedRepositoryNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *UpdateMavenHostedRepositoryNoContent) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/maven/hosted/{repositoryName}][%d] updateRepository1NoContent ", 204)
}

func (o *UpdateMavenHostedRepositoryNoContent) String() string {
	return fmt.Sprintf("[PUT /v1/repositories/maven/hosted/{repositoryName}][%d] updateRepository1NoContent ", 204)
}

func (o *UpdateMavenHostedRepositoryNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateMavenHostedRepositoryUnauthorized creates a UpdateMavenHostedRepositoryUnauthorized with default headers values
func NewUpdateMavenHostedRepositoryUnauthorized() *UpdateMavenHostedRepositoryUnauthorized {
	return &UpdateMavenHostedRepositoryUnauthorized{}
}

/*
	UpdateMavenHostedRepositoryUnauthorized describes a response with status code 401, with default header values.

Authentication required
*/
type UpdateMavenHostedRepositoryUnauthorized struct {
}

// IsSuccess returns true when this update repository1 unauthorized response has a 2xx status code
func (o *UpdateMavenHostedRepositoryUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update repository1 unauthorized response has a 3xx status code
func (o *UpdateMavenHostedRepositoryUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update repository1 unauthorized response has a 4xx status code
func (o *UpdateMavenHostedRepositoryUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this update repository1 unauthorized response has a 5xx status code
func (o *UpdateMavenHostedRepositoryUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this update repository1 unauthorized response a status code equal to that given
func (o *UpdateMavenHostedRepositoryUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *UpdateMavenHostedRepositoryUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/maven/hosted/{repositoryName}][%d] updateRepository1Unauthorized ", 401)
}

func (o *UpdateMavenHostedRepositoryUnauthorized) String() string {
	return fmt.Sprintf("[PUT /v1/repositories/maven/hosted/{repositoryName}][%d] updateRepository1Unauthorized ", 401)
}

func (o *UpdateMavenHostedRepositoryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateMavenHostedRepositoryForbidden creates a UpdateMavenHostedRepositoryForbidden with default headers values
func NewUpdateMavenHostedRepositoryForbidden() *UpdateMavenHostedRepositoryForbidden {
	return &UpdateMavenHostedRepositoryForbidden{}
}

/*
	UpdateMavenHostedRepositoryForbidden describes a response with status code 403, with default header values.

Insufficient permissions
*/
type UpdateMavenHostedRepositoryForbidden struct {
}

// IsSuccess returns true when this update repository1 forbidden response has a 2xx status code
func (o *UpdateMavenHostedRepositoryForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update repository1 forbidden response has a 3xx status code
func (o *UpdateMavenHostedRepositoryForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update repository1 forbidden response has a 4xx status code
func (o *UpdateMavenHostedRepositoryForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this update repository1 forbidden response has a 5xx status code
func (o *UpdateMavenHostedRepositoryForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this update repository1 forbidden response a status code equal to that given
func (o *UpdateMavenHostedRepositoryForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *UpdateMavenHostedRepositoryForbidden) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/maven/hosted/{repositoryName}][%d] updateRepository1Forbidden ", 403)
}

func (o *UpdateMavenHostedRepositoryForbidden) String() string {
	return fmt.Sprintf("[PUT /v1/repositories/maven/hosted/{repositoryName}][%d] updateRepository1Forbidden ", 403)
}

func (o *UpdateMavenHostedRepositoryForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
