// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateConanProxyRepositoryReader is a Reader for the UpdateConanProxyRepository structure.
type UpdateConanProxyRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateConanProxyRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUpdateConanProxyRepositoryNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewUpdateConanProxyRepositoryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateConanProxyRepositoryForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateConanProxyRepositoryNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateConanProxyRepositoryNoContent creates a UpdateConanProxyRepositoryNoContent with default headers values
func NewUpdateConanProxyRepositoryNoContent() *UpdateConanProxyRepositoryNoContent {
	return &UpdateConanProxyRepositoryNoContent{}
}

/*
	UpdateConanProxyRepositoryNoContent describes a response with status code 204, with default header values.

Repository updated
*/
type UpdateConanProxyRepositoryNoContent struct {
}

// IsSuccess returns true when this update repository30 no content response has a 2xx status code
func (o *UpdateConanProxyRepositoryNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update repository30 no content response has a 3xx status code
func (o *UpdateConanProxyRepositoryNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update repository30 no content response has a 4xx status code
func (o *UpdateConanProxyRepositoryNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this update repository30 no content response has a 5xx status code
func (o *UpdateConanProxyRepositoryNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this update repository30 no content response a status code equal to that given
func (o *UpdateConanProxyRepositoryNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *UpdateConanProxyRepositoryNoContent) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/conan/proxy/{repositoryName}][%d] updateRepository30NoContent ", 204)
}

func (o *UpdateConanProxyRepositoryNoContent) String() string {
	return fmt.Sprintf("[PUT /v1/repositories/conan/proxy/{repositoryName}][%d] updateRepository30NoContent ", 204)
}

func (o *UpdateConanProxyRepositoryNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateConanProxyRepositoryUnauthorized creates a UpdateConanProxyRepositoryUnauthorized with default headers values
func NewUpdateConanProxyRepositoryUnauthorized() *UpdateConanProxyRepositoryUnauthorized {
	return &UpdateConanProxyRepositoryUnauthorized{}
}

/*
	UpdateConanProxyRepositoryUnauthorized describes a response with status code 401, with default header values.

Authentication required
*/
type UpdateConanProxyRepositoryUnauthorized struct {
}

// IsSuccess returns true when this update repository30 unauthorized response has a 2xx status code
func (o *UpdateConanProxyRepositoryUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update repository30 unauthorized response has a 3xx status code
func (o *UpdateConanProxyRepositoryUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update repository30 unauthorized response has a 4xx status code
func (o *UpdateConanProxyRepositoryUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this update repository30 unauthorized response has a 5xx status code
func (o *UpdateConanProxyRepositoryUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this update repository30 unauthorized response a status code equal to that given
func (o *UpdateConanProxyRepositoryUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *UpdateConanProxyRepositoryUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/conan/proxy/{repositoryName}][%d] updateRepository30Unauthorized ", 401)
}

func (o *UpdateConanProxyRepositoryUnauthorized) String() string {
	return fmt.Sprintf("[PUT /v1/repositories/conan/proxy/{repositoryName}][%d] updateRepository30Unauthorized ", 401)
}

func (o *UpdateConanProxyRepositoryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateConanProxyRepositoryForbidden creates a UpdateConanProxyRepositoryForbidden with default headers values
func NewUpdateConanProxyRepositoryForbidden() *UpdateConanProxyRepositoryForbidden {
	return &UpdateConanProxyRepositoryForbidden{}
}

/*
	UpdateConanProxyRepositoryForbidden describes a response with status code 403, with default header values.

Insufficient permissions
*/
type UpdateConanProxyRepositoryForbidden struct {
}

// IsSuccess returns true when this update repository30 forbidden response has a 2xx status code
func (o *UpdateConanProxyRepositoryForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update repository30 forbidden response has a 3xx status code
func (o *UpdateConanProxyRepositoryForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update repository30 forbidden response has a 4xx status code
func (o *UpdateConanProxyRepositoryForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this update repository30 forbidden response has a 5xx status code
func (o *UpdateConanProxyRepositoryForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this update repository30 forbidden response a status code equal to that given
func (o *UpdateConanProxyRepositoryForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *UpdateConanProxyRepositoryForbidden) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/conan/proxy/{repositoryName}][%d] updateRepository30Forbidden ", 403)
}

func (o *UpdateConanProxyRepositoryForbidden) String() string {
	return fmt.Sprintf("[PUT /v1/repositories/conan/proxy/{repositoryName}][%d] updateRepository30Forbidden ", 403)
}

func (o *UpdateConanProxyRepositoryForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateConanProxyRepositoryNotFound creates a UpdateConanProxyRepositoryNotFound with default headers values
func NewUpdateConanProxyRepositoryNotFound() *UpdateConanProxyRepositoryNotFound {
	return &UpdateConanProxyRepositoryNotFound{}
}

/*
	UpdateConanProxyRepositoryNotFound describes a response with status code 404, with default header values.

Repository not found
*/
type UpdateConanProxyRepositoryNotFound struct {
}

// IsSuccess returns true when this update repository30 not found response has a 2xx status code
func (o *UpdateConanProxyRepositoryNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update repository30 not found response has a 3xx status code
func (o *UpdateConanProxyRepositoryNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update repository30 not found response has a 4xx status code
func (o *UpdateConanProxyRepositoryNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this update repository30 not found response has a 5xx status code
func (o *UpdateConanProxyRepositoryNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this update repository30 not found response a status code equal to that given
func (o *UpdateConanProxyRepositoryNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *UpdateConanProxyRepositoryNotFound) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/conan/proxy/{repositoryName}][%d] updateRepository30NotFound ", 404)
}

func (o *UpdateConanProxyRepositoryNotFound) String() string {
	return fmt.Sprintf("[PUT /v1/repositories/conan/proxy/{repositoryName}][%d] updateRepository30NotFound ", 404)
}

func (o *UpdateConanProxyRepositoryNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
