// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Eldarrin/nexus-go-api/models"
)

// NewUpdateHelmHostedRepositoryParams creates a new UpdateHelmHostedRepositoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateHelmHostedRepositoryParams() *UpdateHelmHostedRepositoryParams {
	return &UpdateHelmHostedRepositoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateHelmHostedRepositoryParamsWithTimeout creates a new UpdateHelmHostedRepositoryParams object
// with the ability to set a timeout on a request.
func NewUpdateHelmHostedRepositoryParamsWithTimeout(timeout time.Duration) *UpdateHelmHostedRepositoryParams {
	return &UpdateHelmHostedRepositoryParams{
		timeout: timeout,
	}
}

// NewUpdateHelmHostedRepositoryParamsWithContext creates a new UpdateHelmHostedRepositoryParams object
// with the ability to set a context for a request.
func NewUpdateHelmHostedRepositoryParamsWithContext(ctx context.Context) *UpdateHelmHostedRepositoryParams {
	return &UpdateHelmHostedRepositoryParams{
		Context: ctx,
	}
}

// NewUpdateHelmHostedRepositoryParamsWithHTTPClient creates a new UpdateHelmHostedRepositoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateHelmHostedRepositoryParamsWithHTTPClient(client *http.Client) *UpdateHelmHostedRepositoryParams {
	return &UpdateHelmHostedRepositoryParams{
		HTTPClient: client,
	}
}

/*
UpdateHelmHostedRepositoryParams contains all the parameters to send to the API endpoint

	for the update repository 23 operation.

	Typically these are written to a http.Request.
*/
type UpdateHelmHostedRepositoryParams struct {

	// Body.
	Body *models.HelmHostedRepositoryAPIRequest

	/* RepositoryName.

	   Name of the repository to update
	*/
	RepositoryName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update repository 23 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateHelmHostedRepositoryParams) WithDefaults() *UpdateHelmHostedRepositoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update repository 23 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateHelmHostedRepositoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update repository 23 params
func (o *UpdateHelmHostedRepositoryParams) WithTimeout(timeout time.Duration) *UpdateHelmHostedRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update repository 23 params
func (o *UpdateHelmHostedRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update repository 23 params
func (o *UpdateHelmHostedRepositoryParams) WithContext(ctx context.Context) *UpdateHelmHostedRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update repository 23 params
func (o *UpdateHelmHostedRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update repository 23 params
func (o *UpdateHelmHostedRepositoryParams) WithHTTPClient(client *http.Client) *UpdateHelmHostedRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update repository 23 params
func (o *UpdateHelmHostedRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update repository 23 params
func (o *UpdateHelmHostedRepositoryParams) WithBody(body *models.HelmHostedRepositoryAPIRequest) *UpdateHelmHostedRepositoryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update repository 23 params
func (o *UpdateHelmHostedRepositoryParams) SetBody(body *models.HelmHostedRepositoryAPIRequest) {
	o.Body = body
}

// WithRepositoryName adds the repositoryName to the update repository 23 params
func (o *UpdateHelmHostedRepositoryParams) WithRepositoryName(repositoryName string) *UpdateHelmHostedRepositoryParams {
	o.SetRepositoryName(repositoryName)
	return o
}

// SetRepositoryName adds the repositoryName to the update repository 23 params
func (o *UpdateHelmHostedRepositoryParams) SetRepositoryName(repositoryName string) {
	o.RepositoryName = repositoryName
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateHelmHostedRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param repositoryName
	if err := r.SetPathParam("repositoryName", o.RepositoryName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
