// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Eldarrin/nexus-go-api/models"
)

// NewUpdateRubyGemsHostedRepositoryParams creates a new UpdateRubyGemsHostedRepositoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateRubyGemsHostedRepositoryParams() *UpdateRubyGemsHostedRepositoryParams {
	return &UpdateRubyGemsHostedRepositoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateRubyGemsHostedRepositoryParamsWithTimeout creates a new UpdateRubyGemsHostedRepositoryParams object
// with the ability to set a timeout on a request.
func NewUpdateRubyGemsHostedRepositoryParamsWithTimeout(timeout time.Duration) *UpdateRubyGemsHostedRepositoryParams {
	return &UpdateRubyGemsHostedRepositoryParams{
		timeout: timeout,
	}
}

// NewUpdateRubyGemsHostedRepositoryParamsWithContext creates a new UpdateRubyGemsHostedRepositoryParams object
// with the ability to set a context for a request.
func NewUpdateRubyGemsHostedRepositoryParamsWithContext(ctx context.Context) *UpdateRubyGemsHostedRepositoryParams {
	return &UpdateRubyGemsHostedRepositoryParams{
		Context: ctx,
	}
}

// NewUpdateRubyGemsHostedRepositoryParamsWithHTTPClient creates a new UpdateRubyGemsHostedRepositoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateRubyGemsHostedRepositoryParamsWithHTTPClient(client *http.Client) *UpdateRubyGemsHostedRepositoryParams {
	return &UpdateRubyGemsHostedRepositoryParams{
		HTTPClient: client,
	}
}

/*
UpdateRubyGemsHostedRepositoryParams contains all the parameters to send to the API endpoint

	for the update repository 15 operation.

	Typically these are written to a http.Request.
*/
type UpdateRubyGemsHostedRepositoryParams struct {

	// Body.
	Body *models.RubyGemsHostedRepositoryAPIRequest

	/* RepositoryName.

	   Name of the repository to update
	*/
	RepositoryName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update repository 15 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateRubyGemsHostedRepositoryParams) WithDefaults() *UpdateRubyGemsHostedRepositoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update repository 15 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateRubyGemsHostedRepositoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update repository 15 params
func (o *UpdateRubyGemsHostedRepositoryParams) WithTimeout(timeout time.Duration) *UpdateRubyGemsHostedRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update repository 15 params
func (o *UpdateRubyGemsHostedRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update repository 15 params
func (o *UpdateRubyGemsHostedRepositoryParams) WithContext(ctx context.Context) *UpdateRubyGemsHostedRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update repository 15 params
func (o *UpdateRubyGemsHostedRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update repository 15 params
func (o *UpdateRubyGemsHostedRepositoryParams) WithHTTPClient(client *http.Client) *UpdateRubyGemsHostedRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update repository 15 params
func (o *UpdateRubyGemsHostedRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update repository 15 params
func (o *UpdateRubyGemsHostedRepositoryParams) WithBody(body *models.RubyGemsHostedRepositoryAPIRequest) *UpdateRubyGemsHostedRepositoryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update repository 15 params
func (o *UpdateRubyGemsHostedRepositoryParams) SetBody(body *models.RubyGemsHostedRepositoryAPIRequest) {
	o.Body = body
}

// WithRepositoryName adds the repositoryName to the update repository 15 params
func (o *UpdateRubyGemsHostedRepositoryParams) WithRepositoryName(repositoryName string) *UpdateRubyGemsHostedRepositoryParams {
	o.SetRepositoryName(repositoryName)
	return o
}

// SetRepositoryName adds the repositoryName to the update repository 15 params
func (o *UpdateRubyGemsHostedRepositoryParams) SetRepositoryName(repositoryName string) {
	o.RepositoryName = repositoryName
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateRubyGemsHostedRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param repositoryName
	if err := r.SetPathParam("repositoryName", o.RepositoryName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
