// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Eldarrin/nexus-go-api/models"
)

// NewUpdatePypiHostedRepositoryParams creates a new UpdatePypiHostedRepositoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdatePypiHostedRepositoryParams() *UpdatePypiHostedRepositoryParams {
	return &UpdatePypiHostedRepositoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdatePypiHostedRepositoryParamsWithTimeout creates a new UpdatePypiHostedRepositoryParams object
// with the ability to set a timeout on a request.
func NewUpdatePypiHostedRepositoryParamsWithTimeout(timeout time.Duration) *UpdatePypiHostedRepositoryParams {
	return &UpdatePypiHostedRepositoryParams{
		timeout: timeout,
	}
}

// NewUpdatePypiHostedRepositoryParamsWithContext creates a new UpdatePypiHostedRepositoryParams object
// with the ability to set a context for a request.
func NewUpdatePypiHostedRepositoryParamsWithContext(ctx context.Context) *UpdatePypiHostedRepositoryParams {
	return &UpdatePypiHostedRepositoryParams{
		Context: ctx,
	}
}

// NewUpdatePypiHostedRepositoryParamsWithHTTPClient creates a new UpdatePypiHostedRepositoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdatePypiHostedRepositoryParamsWithHTTPClient(client *http.Client) *UpdatePypiHostedRepositoryParams {
	return &UpdatePypiHostedRepositoryParams{
		HTTPClient: client,
	}
}

/*
UpdatePypiHostedRepositoryParams contains all the parameters to send to the API endpoint

	for the update repository 27 operation.

	Typically these are written to a http.Request.
*/
type UpdatePypiHostedRepositoryParams struct {

	// Body.
	Body *models.PypiHostedRepositoryAPIRequest

	/* RepositoryName.

	   Name of the repository to update
	*/
	RepositoryName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update repository 27 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdatePypiHostedRepositoryParams) WithDefaults() *UpdatePypiHostedRepositoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update repository 27 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdatePypiHostedRepositoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update repository 27 params
func (o *UpdatePypiHostedRepositoryParams) WithTimeout(timeout time.Duration) *UpdatePypiHostedRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update repository 27 params
func (o *UpdatePypiHostedRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update repository 27 params
func (o *UpdatePypiHostedRepositoryParams) WithContext(ctx context.Context) *UpdatePypiHostedRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update repository 27 params
func (o *UpdatePypiHostedRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update repository 27 params
func (o *UpdatePypiHostedRepositoryParams) WithHTTPClient(client *http.Client) *UpdatePypiHostedRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update repository 27 params
func (o *UpdatePypiHostedRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update repository 27 params
func (o *UpdatePypiHostedRepositoryParams) WithBody(body *models.PypiHostedRepositoryAPIRequest) *UpdatePypiHostedRepositoryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update repository 27 params
func (o *UpdatePypiHostedRepositoryParams) SetBody(body *models.PypiHostedRepositoryAPIRequest) {
	o.Body = body
}

// WithRepositoryName adds the repositoryName to the update repository 27 params
func (o *UpdatePypiHostedRepositoryParams) WithRepositoryName(repositoryName string) *UpdatePypiHostedRepositoryParams {
	o.SetRepositoryName(repositoryName)
	return o
}

// SetRepositoryName adds the repositoryName to the update repository 27 params
func (o *UpdatePypiHostedRepositoryParams) SetRepositoryName(repositoryName string) {
	o.RepositoryName = repositoryName
}

// WriteToRequest writes these params to a swagger request
func (o *UpdatePypiHostedRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param repositoryName
	if err := r.SetPathParam("repositoryName", o.RepositoryName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
