// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateRubyGemsHostedRepositoryReader is a Reader for the UpdateRubyGemsHostedRepository structure.
type UpdateRubyGemsHostedRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateRubyGemsHostedRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUpdateRubyGemsHostedRepositoryNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewUpdateRubyGemsHostedRepositoryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateRubyGemsHostedRepositoryForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateRubyGemsHostedRepositoryNoContent creates a UpdateRubyGemsHostedRepositoryNoContent with default headers values
func NewUpdateRubyGemsHostedRepositoryNoContent() *UpdateRubyGemsHostedRepositoryNoContent {
	return &UpdateRubyGemsHostedRepositoryNoContent{}
}

/*
	UpdateRubyGemsHostedRepositoryNoContent describes a response with status code 204, with default header values.

Repository updated
*/
type UpdateRubyGemsHostedRepositoryNoContent struct {
}

// IsSuccess returns true when this update repository15 no content response has a 2xx status code
func (o *UpdateRubyGemsHostedRepositoryNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update repository15 no content response has a 3xx status code
func (o *UpdateRubyGemsHostedRepositoryNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update repository15 no content response has a 4xx status code
func (o *UpdateRubyGemsHostedRepositoryNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this update repository15 no content response has a 5xx status code
func (o *UpdateRubyGemsHostedRepositoryNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this update repository15 no content response a status code equal to that given
func (o *UpdateRubyGemsHostedRepositoryNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *UpdateRubyGemsHostedRepositoryNoContent) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/rubygems/hosted/{repositoryName}][%d] updateRepository15NoContent ", 204)
}

func (o *UpdateRubyGemsHostedRepositoryNoContent) String() string {
	return fmt.Sprintf("[PUT /v1/repositories/rubygems/hosted/{repositoryName}][%d] updateRepository15NoContent ", 204)
}

func (o *UpdateRubyGemsHostedRepositoryNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateRubyGemsHostedRepositoryUnauthorized creates a UpdateRubyGemsHostedRepositoryUnauthorized with default headers values
func NewUpdateRubyGemsHostedRepositoryUnauthorized() *UpdateRubyGemsHostedRepositoryUnauthorized {
	return &UpdateRubyGemsHostedRepositoryUnauthorized{}
}

/*
	UpdateRubyGemsHostedRepositoryUnauthorized describes a response with status code 401, with default header values.

Authentication required
*/
type UpdateRubyGemsHostedRepositoryUnauthorized struct {
}

// IsSuccess returns true when this update repository15 unauthorized response has a 2xx status code
func (o *UpdateRubyGemsHostedRepositoryUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update repository15 unauthorized response has a 3xx status code
func (o *UpdateRubyGemsHostedRepositoryUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update repository15 unauthorized response has a 4xx status code
func (o *UpdateRubyGemsHostedRepositoryUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this update repository15 unauthorized response has a 5xx status code
func (o *UpdateRubyGemsHostedRepositoryUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this update repository15 unauthorized response a status code equal to that given
func (o *UpdateRubyGemsHostedRepositoryUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *UpdateRubyGemsHostedRepositoryUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/rubygems/hosted/{repositoryName}][%d] updateRepository15Unauthorized ", 401)
}

func (o *UpdateRubyGemsHostedRepositoryUnauthorized) String() string {
	return fmt.Sprintf("[PUT /v1/repositories/rubygems/hosted/{repositoryName}][%d] updateRepository15Unauthorized ", 401)
}

func (o *UpdateRubyGemsHostedRepositoryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateRubyGemsHostedRepositoryForbidden creates a UpdateRubyGemsHostedRepositoryForbidden with default headers values
func NewUpdateRubyGemsHostedRepositoryForbidden() *UpdateRubyGemsHostedRepositoryForbidden {
	return &UpdateRubyGemsHostedRepositoryForbidden{}
}

/*
	UpdateRubyGemsHostedRepositoryForbidden describes a response with status code 403, with default header values.

Insufficient permissions
*/
type UpdateRubyGemsHostedRepositoryForbidden struct {
}

// IsSuccess returns true when this update repository15 forbidden response has a 2xx status code
func (o *UpdateRubyGemsHostedRepositoryForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update repository15 forbidden response has a 3xx status code
func (o *UpdateRubyGemsHostedRepositoryForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update repository15 forbidden response has a 4xx status code
func (o *UpdateRubyGemsHostedRepositoryForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this update repository15 forbidden response has a 5xx status code
func (o *UpdateRubyGemsHostedRepositoryForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this update repository15 forbidden response a status code equal to that given
func (o *UpdateRubyGemsHostedRepositoryForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *UpdateRubyGemsHostedRepositoryForbidden) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/rubygems/hosted/{repositoryName}][%d] updateRepository15Forbidden ", 403)
}

func (o *UpdateRubyGemsHostedRepositoryForbidden) String() string {
	return fmt.Sprintf("[PUT /v1/repositories/rubygems/hosted/{repositoryName}][%d] updateRepository15Forbidden ", 403)
}

func (o *UpdateRubyGemsHostedRepositoryForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
