// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateMavenProxyRepositoryReader is a Reader for the UpdateMavenProxyRepository structure.
type UpdateMavenProxyRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateMavenProxyRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUpdateMavenProxyRepositoryNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewUpdateMavenProxyRepositoryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateMavenProxyRepositoryForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateMavenProxyRepositoryNoContent creates a UpdateMavenProxyRepositoryNoContent with default headers values
func NewUpdateMavenProxyRepositoryNoContent() *UpdateMavenProxyRepositoryNoContent {
	return &UpdateMavenProxyRepositoryNoContent{}
}

/*
	UpdateMavenProxyRepositoryNoContent describes a response with status code 204, with default header values.

Repository updated
*/
type UpdateMavenProxyRepositoryNoContent struct {
}

// IsSuccess returns true when this update repository2 no content response has a 2xx status code
func (o *UpdateMavenProxyRepositoryNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update repository2 no content response has a 3xx status code
func (o *UpdateMavenProxyRepositoryNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update repository2 no content response has a 4xx status code
func (o *UpdateMavenProxyRepositoryNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this update repository2 no content response has a 5xx status code
func (o *UpdateMavenProxyRepositoryNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this update repository2 no content response a status code equal to that given
func (o *UpdateMavenProxyRepositoryNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *UpdateMavenProxyRepositoryNoContent) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/maven/proxy/{repositoryName}][%d] updateRepository2NoContent ", 204)
}

func (o *UpdateMavenProxyRepositoryNoContent) String() string {
	return fmt.Sprintf("[PUT /v1/repositories/maven/proxy/{repositoryName}][%d] updateRepository2NoContent ", 204)
}

func (o *UpdateMavenProxyRepositoryNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateMavenProxyRepositoryUnauthorized creates a UpdateMavenProxyRepositoryUnauthorized with default headers values
func NewUpdateMavenProxyRepositoryUnauthorized() *UpdateMavenProxyRepositoryUnauthorized {
	return &UpdateMavenProxyRepositoryUnauthorized{}
}

/*
	UpdateMavenProxyRepositoryUnauthorized describes a response with status code 401, with default header values.

Authentication required
*/
type UpdateMavenProxyRepositoryUnauthorized struct {
}

// IsSuccess returns true when this update repository2 unauthorized response has a 2xx status code
func (o *UpdateMavenProxyRepositoryUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update repository2 unauthorized response has a 3xx status code
func (o *UpdateMavenProxyRepositoryUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update repository2 unauthorized response has a 4xx status code
func (o *UpdateMavenProxyRepositoryUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this update repository2 unauthorized response has a 5xx status code
func (o *UpdateMavenProxyRepositoryUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this update repository2 unauthorized response a status code equal to that given
func (o *UpdateMavenProxyRepositoryUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *UpdateMavenProxyRepositoryUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/maven/proxy/{repositoryName}][%d] updateRepository2Unauthorized ", 401)
}

func (o *UpdateMavenProxyRepositoryUnauthorized) String() string {
	return fmt.Sprintf("[PUT /v1/repositories/maven/proxy/{repositoryName}][%d] updateRepository2Unauthorized ", 401)
}

func (o *UpdateMavenProxyRepositoryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateMavenProxyRepositoryForbidden creates a UpdateMavenProxyRepositoryForbidden with default headers values
func NewUpdateMavenProxyRepositoryForbidden() *UpdateMavenProxyRepositoryForbidden {
	return &UpdateMavenProxyRepositoryForbidden{}
}

/*
	UpdateMavenProxyRepositoryForbidden describes a response with status code 403, with default header values.

Insufficient permissions
*/
type UpdateMavenProxyRepositoryForbidden struct {
}

// IsSuccess returns true when this update repository2 forbidden response has a 2xx status code
func (o *UpdateMavenProxyRepositoryForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update repository2 forbidden response has a 3xx status code
func (o *UpdateMavenProxyRepositoryForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update repository2 forbidden response has a 4xx status code
func (o *UpdateMavenProxyRepositoryForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this update repository2 forbidden response has a 5xx status code
func (o *UpdateMavenProxyRepositoryForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this update repository2 forbidden response a status code equal to that given
func (o *UpdateMavenProxyRepositoryForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *UpdateMavenProxyRepositoryForbidden) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/maven/proxy/{repositoryName}][%d] updateRepository2Forbidden ", 403)
}

func (o *UpdateMavenProxyRepositoryForbidden) String() string {
	return fmt.Sprintf("[PUT /v1/repositories/maven/proxy/{repositoryName}][%d] updateRepository2Forbidden ", 403)
}

func (o *UpdateMavenProxyRepositoryForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
