// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateYumHostedRepositoryReader is a Reader for the UpdateYumHostedRepository structure.
type UpdateYumHostedRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateYumHostedRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUpdateYumHostedRepositoryNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewUpdateYumHostedRepositoryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateYumHostedRepositoryForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateYumHostedRepositoryNoContent creates a UpdateYumHostedRepositoryNoContent with default headers values
func NewUpdateYumHostedRepositoryNoContent() *UpdateYumHostedRepositoryNoContent {
	return &UpdateYumHostedRepositoryNoContent{}
}

/*
	UpdateYumHostedRepositoryNoContent describes a response with status code 204, with default header values.

Repository updated
*/
type UpdateYumHostedRepositoryNoContent struct {
}

// IsSuccess returns true when this update repository21 no content response has a 2xx status code
func (o *UpdateYumHostedRepositoryNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update repository21 no content response has a 3xx status code
func (o *UpdateYumHostedRepositoryNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update repository21 no content response has a 4xx status code
func (o *UpdateYumHostedRepositoryNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this update repository21 no content response has a 5xx status code
func (o *UpdateYumHostedRepositoryNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this update repository21 no content response a status code equal to that given
func (o *UpdateYumHostedRepositoryNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *UpdateYumHostedRepositoryNoContent) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/yum/hosted/{repositoryName}][%d] updateRepository21NoContent ", 204)
}

func (o *UpdateYumHostedRepositoryNoContent) String() string {
	return fmt.Sprintf("[PUT /v1/repositories/yum/hosted/{repositoryName}][%d] updateRepository21NoContent ", 204)
}

func (o *UpdateYumHostedRepositoryNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateYumHostedRepositoryUnauthorized creates a UpdateYumHostedRepositoryUnauthorized with default headers values
func NewUpdateYumHostedRepositoryUnauthorized() *UpdateYumHostedRepositoryUnauthorized {
	return &UpdateYumHostedRepositoryUnauthorized{}
}

/*
	UpdateYumHostedRepositoryUnauthorized describes a response with status code 401, with default header values.

Authentication required
*/
type UpdateYumHostedRepositoryUnauthorized struct {
}

// IsSuccess returns true when this update repository21 unauthorized response has a 2xx status code
func (o *UpdateYumHostedRepositoryUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update repository21 unauthorized response has a 3xx status code
func (o *UpdateYumHostedRepositoryUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update repository21 unauthorized response has a 4xx status code
func (o *UpdateYumHostedRepositoryUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this update repository21 unauthorized response has a 5xx status code
func (o *UpdateYumHostedRepositoryUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this update repository21 unauthorized response a status code equal to that given
func (o *UpdateYumHostedRepositoryUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *UpdateYumHostedRepositoryUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/yum/hosted/{repositoryName}][%d] updateRepository21Unauthorized ", 401)
}

func (o *UpdateYumHostedRepositoryUnauthorized) String() string {
	return fmt.Sprintf("[PUT /v1/repositories/yum/hosted/{repositoryName}][%d] updateRepository21Unauthorized ", 401)
}

func (o *UpdateYumHostedRepositoryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateYumHostedRepositoryForbidden creates a UpdateYumHostedRepositoryForbidden with default headers values
func NewUpdateYumHostedRepositoryForbidden() *UpdateYumHostedRepositoryForbidden {
	return &UpdateYumHostedRepositoryForbidden{}
}

/*
	UpdateYumHostedRepositoryForbidden describes a response with status code 403, with default header values.

Insufficient permissions
*/
type UpdateYumHostedRepositoryForbidden struct {
}

// IsSuccess returns true when this update repository21 forbidden response has a 2xx status code
func (o *UpdateYumHostedRepositoryForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update repository21 forbidden response has a 3xx status code
func (o *UpdateYumHostedRepositoryForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update repository21 forbidden response has a 4xx status code
func (o *UpdateYumHostedRepositoryForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this update repository21 forbidden response has a 5xx status code
func (o *UpdateYumHostedRepositoryForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this update repository21 forbidden response a status code equal to that given
func (o *UpdateYumHostedRepositoryForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *UpdateYumHostedRepositoryForbidden) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/yum/hosted/{repositoryName}][%d] updateRepository21Forbidden ", 403)
}

func (o *UpdateYumHostedRepositoryForbidden) String() string {
	return fmt.Sprintf("[PUT /v1/repositories/yum/hosted/{repositoryName}][%d] updateRepository21Forbidden ", 403)
}

func (o *UpdateYumHostedRepositoryForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
