// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Eldarrin/nexus-go-api/models"
)

// NewUpdateRProxyRepositoryParams creates a new UpdateRProxyRepositoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateRProxyRepositoryParams() *UpdateRProxyRepositoryParams {
	return &UpdateRProxyRepositoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateRProxyRepositoryParamsWithTimeout creates a new UpdateRProxyRepositoryParams object
// with the ability to set a timeout on a request.
func NewUpdateRProxyRepositoryParamsWithTimeout(timeout time.Duration) *UpdateRProxyRepositoryParams {
	return &UpdateRProxyRepositoryParams{
		timeout: timeout,
	}
}

// NewUpdateRProxyRepositoryParamsWithContext creates a new UpdateRProxyRepositoryParams object
// with the ability to set a context for a request.
func NewUpdateRProxyRepositoryParamsWithContext(ctx context.Context) *UpdateRProxyRepositoryParams {
	return &UpdateRProxyRepositoryParams{
		Context: ctx,
	}
}

// NewUpdateRProxyRepositoryParamsWithHTTPClient creates a new UpdateRProxyRepositoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateRProxyRepositoryParamsWithHTTPClient(client *http.Client) *UpdateRProxyRepositoryParams {
	return &UpdateRProxyRepositoryParams{
		HTTPClient: client,
	}
}

/*
UpdateRProxyRepositoryParams contains all the parameters to send to the API endpoint

	for the update repository 33 operation.

	Typically these are written to a http.Request.
*/
type UpdateRProxyRepositoryParams struct {

	// Body.
	Body *models.RProxyRepositoryAPIRequest

	/* RepositoryName.

	   Name of the repository to update
	*/
	RepositoryName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update repository 33 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateRProxyRepositoryParams) WithDefaults() *UpdateRProxyRepositoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update repository 33 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateRProxyRepositoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update repository 33 params
func (o *UpdateRProxyRepositoryParams) WithTimeout(timeout time.Duration) *UpdateRProxyRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update repository 33 params
func (o *UpdateRProxyRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update repository 33 params
func (o *UpdateRProxyRepositoryParams) WithContext(ctx context.Context) *UpdateRProxyRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update repository 33 params
func (o *UpdateRProxyRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update repository 33 params
func (o *UpdateRProxyRepositoryParams) WithHTTPClient(client *http.Client) *UpdateRProxyRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update repository 33 params
func (o *UpdateRProxyRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update repository 33 params
func (o *UpdateRProxyRepositoryParams) WithBody(body *models.RProxyRepositoryAPIRequest) *UpdateRProxyRepositoryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update repository 33 params
func (o *UpdateRProxyRepositoryParams) SetBody(body *models.RProxyRepositoryAPIRequest) {
	o.Body = body
}

// WithRepositoryName adds the repositoryName to the update repository 33 params
func (o *UpdateRProxyRepositoryParams) WithRepositoryName(repositoryName string) *UpdateRProxyRepositoryParams {
	o.SetRepositoryName(repositoryName)
	return o
}

// SetRepositoryName adds the repositoryName to the update repository 33 params
func (o *UpdateRProxyRepositoryParams) SetRepositoryName(repositoryName string) {
	o.RepositoryName = repositoryName
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateRProxyRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param repositoryName
	if err := r.SetPathParam("repositoryName", o.RepositoryName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
